### ISSUE TITLE
질문항목이 다소 혼란스러움 

### ISSUE THREAD

**Issue by ironwitz516** [kangtegong/self-learning-cs#1]
Page 185에 나오는 3번 질문이 다소 핵깔리고 보기도 SRAM대신 SDRAM으로 틀리게 제시되었습니다.

**Comment by kangtegong** [comment]
첫 질문을 해주셔서 감사드립니다 :)

확인 해보니 해당 문항은 질문지와 보기가 잘못 출력된 것 같습니다.

질문 문항은 아래와 같이 조금 더 매끄럽게 수정되어야 할 듯 싶습니다.

```
다음 설명을 읽고 SRAM에 대한 설명인지 DRAM에 대한 설명인지 쓰세요.
```

보기 또한 `SRAM` 과 `DRAM`으로 수정되어야 할 것으로 보입니다.

꼼꼼히 읽어주셔서 진심으로 감사드리며,
추후 반영토록 하겠습니다.

소중한 의견 감사드립니다.
강민철 드림
