### ISSUE TITLE
간접 주소 지정 방식 관련 질문

### ISSUE THREAD

**Issue by ChansolPark** [kangtegong/self-learning-cs#10]
좋은 강의 감사드립니다. 간접 주소 지정 방식에 질문이 있어 댓글 남겨봅니다! 
직접 주소 방식은 표현할 수 있는 주소의 크기가 제한되기때문에 간접 주소 지정 방식을 사용한다고 설명해주셨는데요. 
제가 든 의문점은 "결국 간접 주소 지정 방식에서의 가리키는 주소도, 직접 주소 지정 방식과 같은 메모리 주소일텐데 다른점이 있을까?" 였습니다. 
그렇다면 '주어진 비트 내에서 표현 가능한 주소값' 중 하나를 선택해 해당 주소값에 '실제 데이터가 저장되어 있는 큰 주소 값'을 넣어두는 건가요? 
다만 그러면 또 드는 생각이, 만약 메모리 내에 '주어진 비트 내에서 표현 가능한 주소값'이 모두 사용중이라면 어떻게 되는거지? 입니다. 구글링을 해봐도 해당 내용에 대한 해답을 얻지 못해 질문을 남깁니다 ㅠㅠ 
다시 한번 좋은 강의 너무 감사드립니다 !!

**Comment by kangtegong** [comment]
안녕하세요,
유효주소의 크기를 기준으로 따져보시길 바랍니다.
유효주소의 크기만을 따지자면 직접 주소 지정 방식보다
간접 주소 지정 방식이 더 클 수 밖에 없습니다 (본문에 나온 그림을 참고해보세요 :) )
그리고 메모리의 주소보다 더 큰 데이터의 경우 단순히 여러 주소에 걸쳐 나누어 저장되게 됩니다.
그리고 메모리의 주소값이 꽉 차 있을 경우에 어떻게 동작하는지는 [운영체제] 파트를 보면 나와 있는데요,
기존에 저장되어 있던 내용 중 현재 많이 실행되지 않는 정보만 보조기억장치로 내보내기고 (이를 swap out이라고 합니다)
그 내용이 있던 자리에 새로운 정보가 저장됩니다 (이를 swap in이라고 합니다)
