### ISSUE TITLE
프로세스 관련 질문 p341 등등

### ISSUE THREAD

**Issue by popu0405** [kangtegong/self-learning-cs#100]
p341
예를 들어 워드 프로세서에서는 사용자로부터 입력을 받는 프로세스와 입력한 내용의 맞춤법을 검사하는 프로세스, 입력한 애용을 화면에 출력해 주는 프로세스 등이 있습니다. 이 프로세스들은 각기 다른 독립적인 프로세스이지만 곧오의 목표를 위해 서로 협력하는 존재입니다. 

질문)
워드프로세스는 하나이고 스레드가 여러개 실행되는거 아닌가요?
프로세스 설명에서도 비슷하게 구술되어있어서 아주 헷갈립니다. 
ex) ls명령어, 참조 실행코드 및 대부분의 서술 
워드키면 워드에서 여러 프로세스가 실행되는게 맞나요? 아님 그냥 프로세스(스레드) 퉁쳐서 설명해서 저렇게 구술하신건가요?
fork-exec가 발생한건가요 아닌가요?

**Comment by kangtegong** [comment]
안녕하세요

책의 [멀티 프로세스] 예시(fork)로 제시해 드렸듯 여러 개의 프로세스로 구성될 수 있습니다.
여러 프로세스로 만들 수도 있고
여러 스레드로 만들 수도 있습니다 :)
멀티 프로세스 기반으로 구현할지, 
멀티 스레드 기반으로 구현할지 
구체적인 구현 방식은 개발자가 임의로 선택할 수 있고, 
책에서는 그 중 하나의 예시를 제시한 것입니다 :)
