### ISSUE TITLE
운영체제 이중모드에 관해 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by popu0405** [kangtegong/self-learning-cs#101]
P273 cpu가 사용자 모드로 실행중인지, 커널 모드로 실행 중인지는 플래그 레지스터 플래그로 알수 있다. 

1) 운영체제가 응용프로그램이 직접 하드웨어의 접근을 막기위해 이중모드로 구현을 한것인가요?

2) 1번이 맞다면 시스템 콜을 통해서만 하드웨어에 접촉이 가능한데 굳이 cpu가 사용자/커널 모드를 판별할 필요가 있나요?
    어짜피 하드웨어를 직접 제어하는건 커널에서만 가능한데 왜 그걸 일일이 저장을 해놓는거죠?
   
3) 응용 프로그램이 직접 하드웨어에 접근하지 못하는 말은 커널에 특정 요청(함수)를 하면 (커널이 하드웨어 접근이 일어난) 후 반환값을 받아서 자원을 사용하는게 아닌건가요?

**Comment by kangtegong** [comment]
안녕하세요

1. 접 하드웨어의 접근을 막기위해 이중모드로 구현을 한것인가요?
2. 프로그램 실행 관점에서 (CPU가 처리하는 명령어의 관점에서) 볼때 커널 영역을 실행할 때와 사용자 영역을 실행할 때 크게 다르지 않습니다. 실행하는 명ㄹ여어가 운영체제의 것인지 사용자 프로세스의 것인지 구분할 필요가 있습니다.
3. 네 커널의 코드를 실행하여 자원에 접근하는 셈입니다.
