### ISSUE TITLE
p331 SRT 관련 궁금사항이 있습니다.

### ISSUE THREAD

**Issue by popu0405** [kangtegong/self-learning-cs#102]
최소 잔여 시간 우선 스케줄링
...
최소 잔여 시간 우선 스케줄링 하에서 프로세스들은 정해진 타임 슬라이스만큼 CPU를 사용하되, CPU를 사용할 다음 프로세스로는 남아있는 작업 시가이 가장 적은 프로세스가 선택됩니다. 

해당 설명이 맞나요?
그냥 해당작업보다 짧은 잔여시간 프로세스를 먼저 끝까지 처리하는 타임 슬라이스가 없는 선점형 프로세스 스케줄링 아닌가요?

**Comment by kangtegong** [comment]
안녕하세요 

작업 시간이 가장 작더라도 타임 슬라이스만큼 실행합니다.
가령 타임 슬라이스가 1ms, 가장 작업 시간이 작은 프로세스의 시간이 2ms라고 가정했을 때
1ms 이상 실행되지 않습니다.

**Comment by popu0405** [comment]
Shortest remaining time, also known as shortest remaining time first (SRTF), is a scheduling method that is a preemptive version of shortest job next scheduling. In this scheduling algorithm, the process with the smallest amount of time remaining until completion is selected to execute. Since the currently executing process is the one with the shortest amount of time remaining by definition, and since that time should only reduce as execution progresses, the process will either run until it completes or get pre-empted if a new process is added that requires a smaller amount of time.

Shortest remaining time is advantageous because short processes are handled very quickly. The system also requires very little overhead since it only makes a decision when a process completes or a new process is added, and when a new process is added the algorithm only needs to compare the currently executing process with the new process, ignoring all other processes currently waiting to execute.

Like shortest job next long processes may be held off indefinitely if short processes are continually added

https://en.wikipedia.org/wiki/Shortest_remaining_time

여기서 타임 슬라이스가 존재한다는게 어느 부분인가요?

**Comment by kangtegong** [comment]
안녕하세요

" is a scheduling method that is a **preemptive** version of shortest job next scheduling. "

preemptive는 영어로 선점형이라는 뜻입니다.

선점형 스케줄링은 타임 슬라이스를 수반합니다


`선점 스케줄링(preemptive scheduling)은 시분할 시스템에서 타임 슬라이스가 소진되었거나, 인터럽트나 시스템 호출 종료 시에 더 높은 우선 순위 프로세스가 발생 되었음을 알았을 때, 현 실행 프로세스로부터 강제로 CPU를 회수하는 것을 말한다.
`
https://ko.wikipedia.org/wiki/%EC%84%A0%EC%A0%90_%EC%8A%A4%EC%BC%80%EC%A4%84%EB%A7%81

**Comment by popu0405** [comment]
SRT가 시분할 스케줄링이 맞는지 여쭙는건데, 선점형 스케줄링은 모두 시분할 스케줄링을 수반한다고 설명하시고 참조 내용은

선점 스케줄링은 시분할 소진시 OR (인터럽트 OR 시스템호출 종료시 우선순위 발생) 때 강제로 CPU를 회수한다는 말인다.
=> 설명인 즉슨 선점 스케쥴링은 모두 타임 슬라이스를 수반하지 않는다.

설명이 좀 황당한것같네요. 
네 알겠습니다. 다른 서적 참조하는게 나아보이네요.

**Comment by NoelClay** [comment]
[`SRT 링크`](https://en.wikipedia.org/wiki/Shortest_remaining_time)


제가 궁금했던 질문이랑 이어지는 질문이라 여기에 코멘트 달아보려고 합니다. 저자님. 
[``](<p><a href="https://commons.wikimedia.org/wiki/File:Shortest_remaining_time.png#/media/File:Shortest_remaining_time.png"><img src="https://upload.wikimedia.org/wikipedia/commons/3/39/Shortest_remaining_time.png" alt="Shortest remaining time.png" height="471" width="1133"></a><br>By <a href="//commons.wikimedia.org/w/index.php?title=User:Maxtremus&amp;action=edit&amp;redlink=1" class="new" title="User:Maxtremus (page does not exist)">Maxtremus</a> - <span class="int-own-work" lang="en">Own work</span>, <a href="http://creativecommons.org/publicdomain/zero/1.0/deed.en" title="Creative Commons Zero, Public Domain Dedication">CC0</a>, <a href="https://commons.wikimedia.org/w/index.php?curid=44723383">Link</a></p>)

위키링크에 이 이미지를 보시면 마치 타임슬라이스가 적용되지 않는 알고리즘인 마냥 bursttime 6 짜리인 p5가 바로 우선순위가 밀려 p 6 7 8 9 10에 밀려 마지막에 처리되는게 이 위키 설명 그림인데.. 개념적인 내용이겠지만, 타임슬라이스가 고려되는 개념이 맞는건지요. 타임슬라이스가 반드시 선점형에는 무조건 수반되는 개념이 맞는 내용인건지 다시 궁금합니다.. 다시 교차 재검증 해보고 싶습니다.
