### ISSUE TITLE
[문의] 프로세스 테이블은 시스템에 고유하게 존재하는 것 아닌가요??

### ISSUE THREAD

**Issue by ChoiSeonMun** [kangtegong/self-learning-cs#103]
안녕하세요, 저자님. p407에 아래와 같은 내용이 있습니다.

`프로세스마다 각자의 프로세스 테이블을 가지고 있고 각 프로세스의 페이지 테이블들은 메모리에 적재되어 있습니다.`

헌데, [이 자료](https://www.geeksforgeeks.org/process-table-and-process-control-block-pcb/)에서는 프로세스 테이블을 아래와 같이 설명하고 있습니다.

`The process table is an array of PCBs, which logically contains a PCB for all of the current processes in the system.`

혹시 오탈자일까요? 의도하신 것은 `프로세스마다 각자의 프로세스 페이지 테이블을 가지고 있고 이 페이지 테이블들은 메모리에 적재되어 있습니다.`일까요?

**Comment by kangtegong** [comment]
앗 넵 맞습니다 
제시해 주신 부분은 오타입니다
다음 문장이 맞습니다


**프로세스마다 각자의 프로세스 페이지 테이블을 가지고 있고 이 페이지 테이블들은 메모리에 적재되어 있습니다.**

다음 쇄에 잊지 않고 꼭 반영하겠습니다

꼼꼼히 읽어주셔서 정말 감사드립니다.
감사합니다.

**Comment by koir1100** [comment]
저자님 안녕하세요.
2년 전에 관련 내용 수정된 기록이 있습니다.

> [https://github.com/kangtegong/self-learning-cs/issues/43](#43)

혹시 다른 의미를 가지고 있어서 말씀 주신건지 궁금합니다.
확인 부탁드리겠습니다. 감사합니다.

**Comment by kangtegong** [comment]
> 저자님 안녕하세요. 2년 전에 관련 내용 수정된 이슈가 있어 보여서 댓글 드립니다.
> 
> > [#43](https://github.com/kangtegong/self-learning-cs/issues/43)
> 
> 혹시 다른 의미를 가지고 있어서 말씀 주신건지 궁금합니다. 확인 부탁드리겠습니다. 감사합니다.

아, 이전에 언급된 적이 있었던 오타였군요.
확인해 보니 수정 반영하도록 이미 출판사 측에 언급드렸었습니다 :)
아마 최신 쇄에는 반영되어 있을 것으로 보입니다. 

감사합니다.
