### ISSUE TITLE
[문의] 14-2의 마무리 문제 중 2번 문제에 관한 질문이 있습니다.

### ISSUE THREAD

**Issue by ChoiSeonMun** [kangtegong/self-learning-cs#104]
예시에는 참조 비트가 0, 수정 비트가 1로 되어 있는데요. 수정이 일어났는데 참조가 일어나지 않는 경우도 있나요 ?? 🤔

**Comment by kangtegong** [comment]
안녕하세요
하단 링크의 답변을 참고 바랍니다

https://github.com/kangtegong/self-learning-cs/issues/95#issuecomment-2141096482
