### ISSUE TITLE
학습하여 정리했던 내용을 블로그에 올려도 될까요?

### ISSUE THREAD

**Issue by larry1121** [kangtegong/self-learning-cs#106]
안녕하세요! 저자님 덕분에 cs공부에 갈피가 잡힌것 같습니다!
기록용으로 제가 간단히 정리한 책 요약본을 출처와 함께 블로그에 게시해도 되는지 문의드립니다!
아래는 예시입니다.

![Screenshot_20241015_122737_Drive](https://github.com/user-attachments/assets/f5f1a0a6-57b2-498b-9ef9-1b53b73ada77)
![Screenshot_20241015_122815_Drive](https://github.com/user-attachments/assets/bfc67185-c216-4eb6-b460-1828de191fee)

**Comment by kangtegong** [comment]
안녕하세요 출처만 명시해 주신다면 얼마든지 가능합니다 :)
