### ISSUE TITLE
좋은 책 감사합니다! 코드로 책 예제를 설명해준 부분들이 있는데 대부분이 파이썬과 C/C++ 이더라구요.  혹시 가능하시면 자바로도 제공해주실 수 있으실까요?

### ISSUE THREAD

**Issue by inmoG** [kangtegong/self-learning-cs#11]

**Comment by kangtegong** [comment]
안녕하세요^^ 감사합니다.
네, 자바 코드로도 추후 추가해드리겠습니다.
지금은 개인적 일정이 바빠 아마 다음 달 정도에는 추가가 될 듯 한데,
아래의 링크를 보며 학습해보시면 좋을 듯 합니다.

https://byul91oh.tistory.com/249
https://wikidocs.net/230
