### ISSUE TITLE
추가 강의는 언제쯤 더 올라올까요 ? 

### ISSUE THREAD

**Issue by kickbell** [kangtegong/self-learning-cs#12]
안녕하세요. 금일 11월 6일 기준 21강까지 업로드가 된 것 같아요. 

책 으로보니까 전체 15챕터 중에 7챕터 정도까지니까 한 중간정도? 올라간 것 같더라구요. 

혹시 나머지 8챕터부터 15챕터까지의 강의는 언제쯤 올라오는지 알 수 있을까요 ? 

아무래도 후반부가 운영체제라 중요하잖아요. 아니면 책에 따로 코드?같은게 있어서 그걸로 인증하면 볼 수있는걸까요 ? 

열심히 정주행중인데 강의가 중간에 끊겨있는 것 같아 글남깁니다.

**Comment by kangtegong** [comment]
안녕하세요, 8강은 내일 즈음 업로드 될 예정입니다.
원칙적으로 한 주에 한 장씩 올리고 있었으나
최근 개인적인 사정으로 업로드가 지연되고 있었습니다.
빠르게 작업 중이니 조금만 기다려주시기바랍니다.
감사합니다.

**Comment by kickbell** [comment]
아아 넹.. 아닙니다. 강의 기다렸다가 나중에 한번에 보거나 그냥 책으로 보면 되요. 강의가 아무래도 보기 더 편하긴 해서 여쭤봤어요. 답변 감사합니다.
