### ISSUE TITLE
p.151 오탈자

### ISSUE THREAD

**Issue by CodingJBH** [kangtegong/self-learning-cs#13]
p. 151 맨 아래 2번째 줄부터
데이터 버퍼 레지스터, 데이터 주소 레지스터
데이터 부분 메모리로 바꾸면 되겠죠?

**Comment by kangtegong** [comment]
네, 맞습니다 :)
다음 인쇄에서 반영될 예정입니다.
짚어주셔서 감사드립니다.

**Comment by CodingJBH** [comment]
유튜브 수업 잘 듣고 있습니다. 감사합니다~
