### ISSUE TITLE
생산자 소비자 자바코드

### ISSUE THREAD

**Issue by parksiseo** [kangtegong/self-learning-cs#16]
public class ConstruntorConsumerTest {
	public static int sum=10;
	
	public static void main(String[] args) throws InterruptedException {
		
		Thread constructor=new Thread(()->{
			for(int j=0;j<100000;j++) {
				sum++;				
			}				
		});		
		Thread consumer=new Thread(()->{
			for(int j=0;j<100000;j++) {
				sum--;
			}
		});
		constructor.start();
		consumer.start();
		
		constructor.join();
		consumer.join();
		System.out.println(sum);
		
	}//메인

}//클래스

맞게 작성 했는거 같은데 혹시나 필요 하실 분이 있으실 거 같아서 올려봅니다

**Comment by kangtegong** [comment]
좋은 정보 감사드립니다! :)
