### ISSUE TITLE
선생님 동기화 기법 뮤텍스락,세마포,모니터 질문 드려요

### ISSUE THREAD

**Issue by cjftna** [kangtegong/self-learning-cs#17]
선생님 안녕하세요 
책 정말 잘 읽고 있습니다
다름이 아니라 책에 나온 동기화 기법 중에
뮤텍스락은 마치 자바에서 synchronized블락을 하나 설정하는것처럼 보이고
세마포어는 자바에서 object클래스의 wait&notify를 설정하는거 같고
모니터는 reentrant Lock과&condition을 이용하는것과 매우 흡사하던데   
자바에서 위 3가지 동기화 기법이 각각 뮤텍스락 세마포어 모니터를 구현해서 만든 것이 맞나요??

**Comment by kangtegong** [comment]
네 그렇습니다 :)
