### ISSUE TITLE
입출력장치 파트 (DMA, 인터럽트 등)

### ISSUE THREAD

**Issue by hjcdg1** [kangtegong/self-learning-cs#18]
안녕하세요 선생님. 혼공컴운 서적 덕분에 잘 공부하고 있습니다. 현재 입출력장치 파트를 공부 중인데, 관련하여 질문이 있어 이렇게 글을 올려요.

입출력 방식에는 크게 세 가지(프로그램 입출력, 인터럽트 기반 입출력, DMA 입출력)이 있다고 하셨습니다. 그리고 DMA 입출력을 설명하실 때 시스템 버스의 사용 횟수를 최소화하기 위해 입출력 버스를 따로 두고, 입출력장치들은 그 입출력 버스를 통해 DMA 컨트롤러와 연결될 뿐 직접적으로 시스템 버스에는 연결되지 않는다 하셨습니다.

근데 그렇다면 프로그램 입출력 방식을 사용할 때는(즉, 메모리를 굳이 거치는 게 아니라 명령어를 통해 입력장치로부터 CPU의 레지스터로 데이터를 읽어오거나 CPU의 레지스터에서 출력장치로 데이터를 내보내거나 할 때는) CPU가 해당 입출력장치와 어떻게 소통하나요? 입출력장치는 DMA 컨트롤러를 통해서만 시스템 버스와 연결되어 있는데, 그렇다면 프로그램 입출력 방식을 사용할 때도 CPU가 DMA 컨트롤러를 거쳐서 입출력장치와 통신해야 하는 건지 궁금합니다. 그리고 인터럽트 기반 입출력 방식에서도 동일한 의문이 생깁니다. 입출력장치가 인터럽트 요청 신호를 보내서 인터럽트 서비스 루틴을 실행했을 때 해당 루틴도 어찌 됐든 해당 입출력장치에 접근이 가능해야 할 텐데 이때도 DMA 컨트롤러를 거칠 수밖에 없는지요!

다음으로, 여러 입출력장치가 보내는 인터럽트 요청 신호들의 우선순위를 판별해주는 PIC는 DMA 컨트롤러와는 별개로 각종 입출력장치와 연결된 구조일까요? 즉, 한 입출력장치의 입장에서 봤을 때 입출력 버스를 통해 DMA 컨트롤러와도 연결되어 있고 또 다른 핀으로는 PIC에도 연결된 구조일까요?

마지막으로, 여러 입출력장치가 인터럽트 요청 신호를 보낸 경우에, 하나(A)를 처리하고 나면 나머지들 중에서 또 하나(B)를 골라 다음 처리를 이어가야 할 텐데, 그러기 위해서는 PIC에 입력되던 A의 인터럽트 요청 신호를 리셋하는 절차가 필요할 것 같은데 이게 맞는지 궁금하고, 또한 인터럽트 플래그뿐만 아니라 PIC가 최종적으로 건네준 인터럽트 요청 신호를 받아도 되는지 확인하려면 현재 처리 중인 작업의 우선순위도 어딘가에 저장을 하고 있고 이것과 비교해야 할 것 같은데, 이는 CPU 내 레지스터에 저장이 되고 인터럽트 서비스 루틴이 실행될 때마다 저장되는 '어떠한 정보'에도 그것이 포함되는 게 맞을까요?

**Comment by kangtegong** [comment]
안녕하세요, 하나씩 답변드리겠습니다 :)

프로그램 입출력 방식/인터럽트를 사용할 때는(즉, 메모리를 굳이 거치는 게 아니라 명령어를 통해 입력장치로부터 CPU의 레지스터로 데이터를 읽어오거나 CPU의 레지스터에서 출력장치로 데이터를 내보내거나 할 때는) CPU가 해당 입출력장치와 어떻게 소통하나요? 

>> 네, 이론적으로 DMA를 사용한다면 DMA 컨트롤러를 거쳐야 합니다.
여담으로 이게 느리다고 생각 들 수 있겠으나, 최근 IO 프로세서, IO 채널의 발전으로 입출력 명령어도 빠르게 처리될 수 있습니다.
(입출력장치 파트 뒷편을 보면 IO 프로세서, IO 채널과 관련한 이야기가 있을 거에요^^) 


입출력장치의 입장에서 봤을 때 입출력 버스를 통해 DMA 컨트롤러와도 연결되어 있고 또 다른 핀으로는 PIC에도 연결된 구조일까요?
>> 별개의 핀으로 보는 것이 맞습니다. (입출력장치에는 하나로 연결될지라도 적어도 CPU에는 별개의 핀으로 연결됩니다) 아래 링크를 참고 바랍니다.

https://people.ece.cornell.edu/land/courses/ece4760/PIC32/index_DMA.html

마지막으로, 여러 입출력장치가 인터럽트 요청 신호를 보낸 경우에, 하나(A)를 처리하고 나면 나머지들 중에서 또 하나(B)를 골라 다음 처리를 이어가야 할 텐데, 그러기 위해서는 PIC에 입력되던 A의 인터럽트 요청 신호를 리셋하는 절차가 필요할 것 같은데 이게 맞는지 궁금하고,
>> 리셋이 아닌 문맥(context)을 백업합니다. 혹시 아직 [운영체제] 파트에서 다루는 [문맥 교환]을 학습하지 않으셨다면 이건 해당 부분을 읽어보시면 이건 이해가 빠르실 것 같은데요,
간략히 요약해드리자면 운영체제(Windows, macOS, Linux, Android, iOS, ...)는 현재 실행 중인 프로그램들(프로세스라고 합니다)을 빠르게 번갈아가며 실행할 수 있도록 관리합니다. 각 프로세스가 번갈아가며 수행되더라도 이전의 실행을 복구해서 다시 실행될 수 있도록 프로세스마다 문맥이라는 것이 있는데,
인터럽트 서비스 루틴도 프로그램이기 때문에 문맥이 있습니다. 그 문맥을 백업하고 복구함으로써 인터럽트 서비스 루틴을 재개할 수 있습니다.

또한 인터럽트 플래그뿐만 아니라 PIC가 최종적으로 건네준 인터럽트 요청 신호를 받아도 되는지 확인하려면 현재 처리 중인 작업의 우선순위도 어딘가에 저장을 하고 있고 이것과 비교해야 할 것 같은데, 이는 CPU 내 레지스터에 저장이 되고 인터럽트 서비스 루틴이 실행될 때마다 저장되는 '어떠한 정보'에도 그것이 포함되는 게 맞을까요?
>> 정확하게는 인터럽트 서비스 루틴(CPU가 실행할 프로그램)마다 우선순위가 있고, CPU는 그 우선순위별로 실행을 할 뿐입니다.
그리고 PIC에도 현재 처리 중인 인터럽트 우선순위 레벨을 명시한 레지스터가 있습니다. 

하단 링크에서 PIC의 한 종류의 내부 구성을 다루고 있는데 
Interrupt service register (ISR), Interrupt request register (IRR), Interrupt mask register (IMR)
를 참고 바랍니다.

https://www.geeksforgeeks.org/8259-pic-microprocessor/

좋은 질문 감사합니다.
추가로 궁금한 점이 생긴다면 다시 질문 올려주셔도 좋습니다.

감사합니다.

**Comment by kangtegong** [comment]
안녕하세요, 하나씩 답변드리겠습니다 :)

> 프로그램 입출력 방식/인터럽트를 사용할 때는(즉, 메모리를 굳이 거치는 게 아니라 명령어를 통해 입력장치로부터 CPU의 레지스터로 데이터를 읽어오거나 CPU의 레지스터에서 출력장치로 데이터를 내보내거나 할 때는) CPU가 해당 입출력장치와 어떻게 소통하나요? 

네, 이론적으로 DMA를 사용한다면 DMA 컨트롤러를 거쳐야 합니다.
여담으로 이게 느리다고 생각 들 수 있겠으나, 최근 IO 프로세서, IO 채널의 발전으로 입출력 명령어도 빠르게 처리될 수 있습니다.
(입출력장치 파트 뒷편을 보면 IO 프로세서, IO 채널과 관련한 이야기가 있을 거에요^^) 


> 입출력장치의 입장에서 봤을 때 입출력 버스를 통해 DMA 컨트롤러와도 연결되어 있고 또 다른 핀으로는 PIC에도 연결된 구조일까요?

별개의 핀으로 보는 것이 맞습니다. (입출력장치에는 하나로 연결될지라도 적어도 CPU에는 별개의 핀으로 연결됩니다) 아래 링크를 참고 바랍니다.

https://people.ece.cornell.edu/land/courses/ece4760/PIC32/index_DMA.html

> 마지막으로, 여러 입출력장치가 인터럽트 요청 신호를 보낸 경우에, 하나(A)를 처리하고 나면 나머지들 중에서 또 하나(B)를 골라 다음 처리를 이어가야 할 텐데, 그러기 위해서는 PIC에 입력되던 A의 인터럽트 요청 신호를 리셋하는 절차가 필요할 것 같은데 이게 맞는지 궁금하고,

리셋이 아닌 문맥(context)을 백업합니다. 혹시 아직 [운영체제] 파트에서 다루는 [문맥 교환]을 학습하지 않으셨다면 이건 해당 부분을 읽어보시면 이건 이해가 빠르실 것 같은데요,
간략히 요약해드리자면 운영체제(Windows, macOS, Linux, Android, iOS, ...)는 현재 실행 중인 프로그램들(프로세스라고 합니다)을 빠르게 번갈아가며 실행할 수 있도록 관리합니다. 각 프로세스가 번갈아가며 수행되더라도 이전의 실행을 복구해서 다시 실행될 수 있도록 프로세스마다 문맥이라는 것이 있는데,
인터럽트 서비스 루틴도 프로그램이기 때문에 문맥이 있습니다. 그 문맥을 백업하고 복구함으로써 인터럽트 서비스 루틴을 재개할 수 있습니다.

> 또한 인터럽트 플래그뿐만 아니라 PIC가 최종적으로 건네준 인터럽트 요청 신호를 받아도 되는지 확인하려면 현재 처리 중인 작업의 우선순위도 어딘가에 저장을 하고 있고 이것과 비교해야 할 것 같은데, 이는 CPU 내 레지스터에 저장이 되고 인터럽트 서비스 루틴이 실행될 때마다 저장되는 '어떠한 정보'에도 그것이 포함되는 게 맞을까요?

정확하게는 인터럽트 서비스 루틴(CPU가 실행할 프로그램)마다 우선순위가 있고, CPU는 그 우선순위별로 실행을 할 뿐입니다.
그리고 PIC에도 현재 처리 중인 인터럽트 우선순위 레벨을 명시한 레지스터가 있습니다. 

하단 링크에서 PIC의 한 종류의 내부 구성을 다루고 있는데 
Interrupt service register (ISR), Interrupt request register (IRR), Interrupt mask register (IMR)
를 참고 바랍니다.

https://www.geeksforgeeks.org/8259-pic-microprocessor/

좋은 질문 감사합니다.
추가로 궁금한 점이 생긴다면 다시 질문 올려주셔도 좋습니다.

감사합니다.

**Comment by hjcdg1** [comment]
답변 감사합니다. 결과적으로 제가 이해한 건 다음과 같은데, 혹시 맞는지 확인 부탁드려도 될까요?

> 프로세스 A를 실행하고 있을 때 특정 인터럽트가 발생했다고 가정하자. 그러면 프로세스 A의 문맥을 PCB에 저장하고, 해당 인터럽트의 서비스 루틴을 실행한다. 이때부터는 사용자 모드가 아닌 커널 모드가 된다. 인터럽트 서비스 루틴의 실행이 종료되고 나면 다시 프로세스 A의 문맥을 PCB에서 복원하여 프로세스 A의 실행을 재개할 수도 있고, 다른 프로세스 B의 문맥을 PCB에서 복원하여 프로세스 B로 문맥 전환을 할 수도 있다.  그 결정은 여러 가지 상황을 토대로 스케쥴링 로직이 도출한다. 여기서 말하는 인터럽트란 시스템 콜, 즉 소프트웨어 인터럽트일 수도 있고, 하드웨어 인터럽트일 수도 있다. 원리는 같다.<br />
만약 하드 디스크에서 데이터를 읽기 위한 시스템 콜이라면, 인터럽트 서비스 루틴은 DMA 컨트롤러에게 해당 연산을 위임한 뒤 DMA 컨트롤러로부터 인터럽트가 올 때까지 마냥 기다리기만 할 수 없으므로 다른 프로세스의 문맥을 PCB에서 복원함으로써 해당 프로세스로 문맥을 전환하여 그 시간을 활용할 것이다.<br />
만약 타이머 인터럽트라면, 인터럽트 서비스 루틴은 대기 중인 다른 프로세스들 중에 어떤 프로세스로 문맥을 전환할지 판단하고 마찬가지 원리로 문맥을 전환할 것이다.

**Comment by kangtegong** [comment]
네 그렇습니다^^

**Comment by hjcdg1** [comment]
답변 감사합니다.

여기서 하나 헷갈리는 부분이 있는데, 프로세스 A를 실행하고 있을 때 인터럽트 X가 발생하여 X의 서비스 루틴을 실행 중이었는데, 우선순위가 더 높은 다른 인터럽트 Y가 발생하면 어떻게 되나요? 이때도 마찬가지로 인터럽트가 발생한 상황이기 때문에 현재 프로세스의 상태를 PCB에 저장해야 할 것 같은데, X의 서비스 루틴도 결국 프로세스 A의 맥락에서 실행되고 있던 거라 이 시점에 해당하는 프로세스 A의 상태를 PCB에 저장하지 않을까 싶은데, 그러면 그 전에(인터럽트 X가 발생했을 때) 저장했던 정보가 사라질 것 같아서요.

혹시 '인터럽트가 발생하여 해당 인터럽트의 서비스 루틴을 호출하기 전에 저장하는 어떠한 정보'라는 것이 PCB에 저장하는 문맥과는 다른 것인지 궁금해졌어요. 다른 것이 아니라면 위 의문이 잘 해결이 되질 않네요 ㅠㅠ 실제로 문맥 전환에 대한 설명을 검색하다 보면 인터럽트 서비스 루틴 실행 '후' 스케쥴러가 판단하여 문맥 전환이 필요하다 싶을 때 기존 프로세스의 상태를 PCB에 저장하고 새로운 프로세스의 상태를 PCB에서 복원한다고 나와 있기도 한데, PCB에 상태를 저장하는 시점이 '인터럽트 서비스 루틴을 실행하기 전'인지 '인터럽트 서비스 루틴 실행 후 문맥 전환이 필요하다고 판단되었을 때'인지 명확히 알고 싶습니다.

답변 부탁드립니다!

**Comment by kangtegong** [comment]
인터럽트가 발생했다고 해서 문맥이 사라지는 것은 아닙니다.  
책에 언급되었듯 문맥은 스택에 저장되어 더 높은 인터럽트 처리 후 언제든 pop되어 실행될 수 있지요.
(꼭 선입선출형태의 스택이 아닌 경우도 있습니다, 중요한건 프로세스별로 문맥은 딱 하나밖에 저장되는건 아니라는 의미입니다
만일 그렇다면 모든 프로세스는 하나의 인터럽트밖에 처리를 못하겠지요)

'인터럽트가 발생하여 해당 인터럽트의 서비스 루틴을 호출하기 전에 저장하는 어떠한 정보'라는 
말씀이 조금 모호한데, 그냥 문맥이라고 생각하셔도 무방할 듯합니다..^^;;
문맥교환은 인터럽트 서비스 루틴 전후로 수행되니까요.

**Comment by hjcdg1** [comment]
답변 감사합니다! 덕분에 잘 공부하고 있습니다. 또 궁금한 게 생기면 다시 질문드리겠습니다 👍
