### ISSUE TITLE
하드웨어적 스레드와 소프트웨어적 스레드 관련 질문

### ISSUE THREAD

**Issue by Taeil-Nam** [kangtegong/self-learning-cs#19]
안녕하세요 선생님,

집필하신 책 참고하면서 멀티스레드 쪽 공부를 하고 있는 중에 궁금한 점이 생겨서 질문드립니다!

기초 다지는데 도움이 정말 많이 됩니다.
좋은 책 만들어주셔서 감사합니다 ㅎㅎ

---

### 질문
- 1코어 2스레드 CPU를 사용한다고 가정.

1. 특정 프로그램이 스레드를 3개 사용하도록 짜여져 있다면, 소프트웨어적 스레드가 3개다! 라고 이해하면 될까요?
2. 위의 프로그램을 실행한다면, CPU 입장에서 하드웨어적 스레드는 2개이므로 프로그램에서 요구하는 소프트웨어 스레드보다 1개가 부족하니까, 부족한 스레드에 대해서 context switching이 일어나면서 프로그램이 실행되는게 맞을까요?

**Comment by kangtegong** [comment]
네, 그렇습니다 :)

**Comment by nutslove** [comment]
안녕하세요.

윗분 질문과 관련해서 저도 비슷한 질문이 있어서 여기에 남깁니다.
151쪽에 "1코어 1스레드 CPU로도 프로그램의 여려 부분을 동시에 실행할 수 있다" 라고 쓰여있는데
엄밀히는 동시(parallel)는 아니고 병행(concurrent)이 맞다고 이해했는데 맞을까요?

**Comment by kangtegong** [comment]
책에서 쓰인 '동시'가 병렬(Parallelism)을 의미하는 것은 아닙니다.
말 그대로 '동일한 시각'(simultaneous)을 나타내기 위해 쓰인 표현입니다.

단일 코어로 다중 스레드를 처리한다고 가정하면 nutslove 말씀이 맞습니다. 
다만 책에서는 예시의 단순화를 위해 
병렬(Parallelism)과 병행(Concurrency)을 구분하지 않았습니다.

**Comment by jemok96** [comment]
감사합니다!
