### ISSUE TITLE
p58, 이진수의 음수표현 질문드립니다.

### ISSUE THREAD

**Issue by Sangyubs** [kangtegong/self-learning-cs#2]
안녕하세요. 
혼공컴운을 공부하던 중 궁금한 점이 있어 질문드립니다.

p58에서 0과 1만으로 음수를 표현해야하기 때문에 2의 보수를 구해 음수로 간주하는데, 결국 음수 양수는 플래그를 사용해 구분한다고 되어있습니다.

그럼 굳이 2의 보수를 쓰지 않고 플래그로만 구분하면 되지 않을까 의문이 듭니다. 
예를 들어 -3은 그냥 이진수 11로 표현하고 플래그를 달면 되는데 굳이 2의 보수로 바꾼 다음 플래그를 다는 이유가 무엇인지 궁금합니다.
감사합니다.

**Comment by kangtegong** [comment]
그렇게 하면 음수와 양수 사이의 사칙 연산에 있어서 일관성이 깨질 수 있습니다.
가령 -3과 1을 더하는 경우를 생각해보세요.

-3의 2의 보수는 101입니다.
여기에 1을 더하면 110이죠?

이는 2(010)의 2의 보수 입니다.

단순히 플래그만을 이용하면 위와 같이 양수와 음수 사이의 연산이 불가하기 때문에 2의 보수를 사용하는 것입니다.

**Comment by Sangyubs** [comment]
감사합니다.
