### ISSUE TITLE
P.98 레지스터 주소 지정 방식

### ISSUE THREAD

**Issue by neont21** [kangtegong/self-learning-cs#20]
P.98의 "레지스터 주소 지정 방식" 설명에 다음과 같은 내용이 있습니다.

> 다만, 레지스터 주소 지정 방식은 직접 주소 지정 방식과 비슷한 문제를 공유합니다. 표현할 수 있는 레지스터 크기에 제한이 생길 수 있다는 점입니다.

그런데 "레지스터 주소 지정 방식"이 가진 이슈는 "직접 주소 지정 방식"보다 "즉시 주소 지정 방식"과 비슷한 것 아닌가 하는 의문이 들어 질문 드립니다.

레지스터가 나타낼 수 있는 데이터 크기가 제한되어 있어, 레지스터가 데이터 그 자체가 아닌 데이터의 주소를 가지고 있도록 하는 방식이 "레지스터 간접 주소 지정 방식"이라고 이해하여 다음과 같은 관계가 성립한다고 이해했는데요, 

||데이터 그 자체 저장|데이터의 주소 저장|
|:-:|:-:|:-:|
|오퍼랜드 필드|즉시 주소 지정 방식|직접 주소 지정 방식|
|레지스터|레지스터 주소 지정 방식|레지스터 간접 주소 지정 방식|
|특징|저장할 수 있는 크기가 제한되어 있어 데이터 크기 한정적|데이터가 메모리 상에 저장된 주소를 저장하여 데이터 크기로부터 자유로움|

직접 주소 지정 방식 : 레지스터 주소 지정 방식
간접 주소 지정 방식 : 레지스터 간접 주소 지정 방식
의 관계가 아니라
즉시 주소 지정 방식 : 레지스터 주소 지정 방식
직접 주소 지정 방식 : 레지스터 간접 주소 지정 방식
라고 인식한 건,

즉시 주소 지정 방식: 저장할 수 있는 데이터 크기가 오퍼랜드 필드 크기만큼으로 제한적.
직접 주소 지정 방식: 표현할 수 있는 유효 주소가 오퍼랜드 필드 크기만큼으로 제한적.
간접 주소 지정 방식: 상대적으로 느리지만 데이터 크기는 자유.

레지스터 주소 지정 방식: 저장할 수 있는 데이터 크기가 레지스터 크기만큼으로 제한적.
레지스터 간접 주소 지정 방식: 표현할 수 있는 유효 주소가 레지스터 크기만큼 제한적?

이런 느낌으로 이해했기 때문인데,

"레지스터 주소 지정 방식"이 "즉시 주소 지정 방식"이 아닌 "직접 주소 지정 방식"에 대응하여 그것과 비슷한 문제를 공유하는 이유를 좀 더 자세히 설명해주시면 감사하겠습니다.

**Comment by kangtegong** [comment]
음 즉시 주소 지정의 문제와 직접 주소 지정의 문제를 칼로 자르듯 구분하기는 어렵다고 봅니다.
즉시 주소 지정이나 직접 주소 지정이나 갖고 있는 문제는 동일합니다.
단순히 표현할 수 있는 크기에 제한이 있다는 점을 다루고 있어요.
그런 점에서 

> 다만, 레지스터 주소 지정 방식은 직접 주소 지정 방식과 비슷한 문제를 공유합니다. 표현할 수 있는 레지스터 크기에 제한이 생길 수 있다는 점입니다.

라는 표현을 썼습니다.
질문자님 표현도 맞습니다. 즉시 주소 지정이나 직접 주소 지정이나 표현할 수 있는 크기에 제한이 있다는 점은 동일하니까요.
