### ISSUE TITLE
P.137 명령어 사이클 그림

### ISSUE THREAD

**Issue by neont21** [kangtegong/self-learning-cs#21]
CPU는 실행 사이클이 끝나고 명령어를 인출하기 전 인터럽트 여부를 확인하고,
인터럽트가 발생한 경우 인터럽트 사이클을 수행한다고 이해했습니다.

그런데 그렇게 되면 P.137의 그림이 다음과 같이 수정되어야 하는 것 아닌가 싶어 질문 드립니다.

![image](https://user-images.githubusercontent.com/47443508/211304419-2d1a0904-60a0-45ab-bc9a-e79670375f3e.png)

**Comment by kangtegong** [comment]
네 맞습니다. 
해당 부분에 대한 표기는 다음 번 인쇄에서 수정 반영할 예정입니다.

꼼꼼하게 읽어주셔서 감사드립니다.
