### ISSUE TITLE
P.215 오탈자 "대용화"

### ISSUE THREAD

**Issue by neont21** [kangtegong/self-learning-cs#22]
> (생략) MLC 타입은 SLC 타입보다 대용화하기 유리합니다.

라는 표현에서 "대용화"라는 어휘를 처음 들어 뭐지 했는데, 다음 페이지의 TLC 타입 설명을 보니 "대용량화"의 오탈자인 것 같아 제보 드립니다.

---

추가로, 이번 장 학습하며 문득 인지한 건데 너무 사소한? 거라 그냥 넘어가려고 하다가 제보하는 김에 같이 언급하자면
확인 문제에서 "보기"를 언급할 때 "〈보기〉"처럼 홑화살괄호를 사용하는 경우와 그렇지 않은 경우가 혼용되고 있더군요.
책의 내용과 직접적으로 관련 있는 부분은 아니긴 하지만 전반적인 책의 퀄리티를 높이기 위해서는 통일하는 쪽이 좋을 것 같아
이런 식으로 작성한 특별한 이유가 있는 게 아니라면 다음 인쇄에는 반영하실 수 있도록 조심스럽게 언급해봅니다. ㅎㅎ

**Comment by kangtegong** [comment]
소중한 제보 감사드립니다. 확인 후 다음 쇄에 일괄 반영하겠습니다.
감사합니다 :)
