### ISSUE TITLE
교재 116p 질문드립니다.

### ISSUE THREAD

**Issue by yjdong9697** [kangtegong/self-learning-cs#23]
교재 p.116 4번 과정에서 제어장치가 메모리 읽기와 관련된 제어신호를 제어버스에 보내는 것은 알겠는데, 이 과정에서 제어장치는 무엇을 입력으로 받는 것인가요?

제어장치의 경우 클락, 플래그, 명령어 레지스터, 받아 제어신호를 내보내는 것으로 이해했는데, 위 상황에서는 명령어 레지스터가 어떤 값이 들어간다고 생각해야하는건가요?

**Comment by kangtegong** [comment]
제어장치는 내부적으로 명령어 (혹은 명령어를 찾기 위한 로직)을 해석해서 그에 맞는 신호를 발생시킵니다.
정확히 어떤 값이 들어가는지는 CPU에 따라 다를 수 있지만, (제시된 그림의 경우) 대략
메모리 읽기 신호 전에 **어떤 메모리에 접근해야 할지에 대한 정보**(=실제 명령어를 찾기 위해 참조해야 할 주소)를 받아들여
이를 해석하고 신호를 발생시킨다고 보면 됩니다.
