### ISSUE TITLE
p.132 인터럽트 요청 신호와 인터럽트 플래그에 관하여 질문이 있습니다.

### ISSUE THREAD

**Issue by jschan0911** [kangtegong/self-learning-cs#24]
안녕하세요 민철님!
어렵고 지루할 수 있는 내용들을 알기 쉽게 설명해주셔서 많은 도움이 됩니다.

책을 통해 공부하던 중, 두 가지 궁금증이 생겨 질문드립니다.

### 1. 인터럽트 요청 신호에 관한 질문
하드웨어 인터럽트 처리 과정에서 
"CPU는 인출 사이클 실행 전에 항상 인터럽트 여부를 확인한다"고 설명해주셨는데, 

이때 CPU가 인터럽트 요청 신호를 확인할 수 있도록 
입출력 장치에서 CPU로 **제어 버스를 통해서** 인터럽트 요청 신호를 보내는 것이 맞나요?

### 2. 인터럽트 플래그에 관한 질문
인터럽트 신호가 도달했을 때 
"인터럽트 플래그를 통해 받아들이는 여부를 결정한다"고 설명해주셨는데, 

이때 CPU가 확인하는 인터럽트 플래그는 
**방금 보낸 인터럽트 요청 신호 안에 포함되어있는 내용**인가요?
**이전 명령어에 의해 생성된 플래그의 내용**인가요?

둘 다 아니라면 어느 시점에 플래그 레지스터에 저장된 정보인가요?

**Comment by kangtegong** [comment]
안녕하세요 :) 좋게 읽어주셔서 감사합니다.

1. 네, 인터럽트 요청 신호는 제어 버스로 전달이 됩니다. CPU는 제어 버스로 들어온 인터럽트 요청 신호가 있는지를 주기적으로 확인하는 것이구요.
2. 이건 인터럽트 요청 신호에 포함되어있다기보다는 이전 명령어에 의해 생성되었다고 봄이 옳습니다. 어떠한 인러럽트 요청 신호가 독립적으로 존재할 때, 그를 처리할지말지를 결정하기 위한 플래그이니까요.

**Comment by jschan0911** [comment]
답변 감사합니다!!
