### ISSUE TITLE
P. 295 확인문제 2번

### ISSUE THREAD

**Issue by neont21** [kangtegong/self-learning-cs#25]
2번 문제의 1번 보기에 다음과 같이 나와 있는데

> ① 문맥 교환은 **빠르게** 수행될수록 좋습니다.

"빠르게"라는 표현이

- 문맥 교환이 이루어지는 주기가 빠른 것인지
- 문맥 교환 과정 자체가 빠르게 실행되는 것인지

중의적으로 해석될 여지가 있어

> ① 문맥 교환은 **자주** 수행될수록 좋습니다.

라고 하는 편이 명확할 것 같다는 제안 드리고자 이슈를 남깁니다.

**Comment by kangtegong** [comment]
좋은 제안 감사드립니다 :)
