### ISSUE TITLE
주소 지정 방식에 관련하여 질문이 있습니다.

### ISSUE THREAD

**Issue by chlahfo** [kangtegong/self-learning-cs#26]
1. 즉시 주소 지정 방식은 오퍼랜드에 연산에 사용할 데이터가 들어있는 방식이기 때문에 연산에 사용할 데이터를 메모리나 레지스터로부터 찾는 과정이 없어서 다른 주소 지정 방식들보다 빠르다고 되어있습니다. 그런데, 데이터를 사용한다는 것은 결국 어딘가에 저장은 되어있다는 뜻일텐데, 메모리나 레지스터에 데이터가 없다면 어디에 있다는 뜻인가요?? CPU 안의 ALU 에 있나요...?

2. 직접 주소 지정 방식과 간접 주소 지정 방식에 대한 차이점은 알겠는데, 이점이 크게 와닿지가 않습니다.직접 주소 지정 방식은 유효 주소를 표현 할 수 있는 범위가 연산 코드의 비트 수만큼 줄기 때문에 제한이 생길 수 있다고 되어있습니다. 그러나 간접 주소 지정방식 또한 유효 주소의 주소도 연산 코드의 비트 수만큼 줄지 않나요?? 결국 유효주소나 유효주소의 주소나 똑같은 메모리 주소일텐데 굳이 유효주소를 더 길게 써야 할 상황이 있나요??더더군다나 간접 주소 지정 방식은 두 번의 메모리 접근이 필요해서 더 느릴텐데 왜 이 방식을 사용하는지 이유를 모르겠습니다.

**Comment by chlahfo** [comment]
3. 애초에 주소 지정 방식에서 명령어의 크기가 16비트 등 한정된 크기일 때 오퍼랜드에 데이터를 즉시 명시하면 데이터의 크기가 한정되어 다양한 주소 지정방식을 쓰는 것을 전제로 하고 있는데, 파이썬과 C언어 기초만 배워서인지 명령어의 크기가 한정된다는 상황이 와닿지 않습니다. 보통 기계어나 어셈블리어의 명령어는 크기가 한정되어 있는건가요??

**Comment by kangtegong** [comment]
1. 즉시 주소 지정 방식은 말 그대로 **명령어 안**에 데이터가 그대로 명시되어있다는 뜻입니다. 명령어가 저장된 공간 = 데이터가 저장된 공간이지요.
2. **연산에 사용될 데이터**를 표현하는 크기만을 기준으로 생각해보세요. 그림을 보시면 유효 주소를 표현하는 공간은 직접 주소 지정보다 간접 주소 지정이 더 큽니다. 그렇기에 더 많은 메모리를 참조할 수 있다는 장점이 있습니다.
3. 그렇습니다. 프로그래밍 언어를 다룰 때에는 크게 와닿지 않을 수 있지만 실제로도 큰 데이터의 경우 내부적으로는 한정된 크기의 단위로 잘려서 메모리에 저장됩니다.

**Comment by chlahfo** [comment]
아하 감사합니다!!
