### ISSUE TITLE
P.323 프로세스 상태 다이어그램

### ISSUE THREAD

**Issue by neont21** [kangtegong/self-learning-cs#27]
준비 큐와 대기 큐가 반영된 프로세스 상태 다이어그램을 보면 다음과 같이 준비 상태가 두 개 존재합니다.

![image](https://user-images.githubusercontent.com/47443508/214971435-c32d23ec-81f4-4ce8-9112-1eda0149aba3.png)

다음과 같이 하나로 표현해도 될 것 같은데 준비 큐가 포함된 준비 상태를 따로 표현하신 이유가 잘 이해가 되지 않아 질문 드립니다.

![image](https://user-images.githubusercontent.com/47443508/214971349-990707db-67b1-40e7-a95a-76d5410440e4.png)

**Comment by kangtegong** [comment]
안녕하세요, 해당 부분은 다음 쇄 반영 예정입니다 :)
꼼꼼히 읽어주셔서 감사합니다.
