### ISSUE TITLE
p.355~356 세마포 `signal` 함수

### ISSUE THREAD

**Issue by neont21** [kangtegong/self-learning-cs#28]
작동하는 코드라기 보다는 pseudo-code라서 큰 문제는 없을 것 같습니다만,
`wait` 함수는
```
wait() {
    while ( S <= 0 )
    ;
    S--;
}
```
와 같이 세미콜론이 있는 반면

`signal` 함수는
```
signal() {
    S++
}
```
와 같이 세미콜론이 생략되어 있어,
일관성을 유지하는 쪽이 좋을 것 같다는 제안 드립니다.

(355페이지 코드만 언급했지만 356페이지 코드도 마찬가지.)

**Comment by kangtegong** [comment]
확인후 필요시 반영하겠습니다. 감사합니다.
