### ISSUE TITLE
멀티 스레드에 관해서 질문드립니다!!!!

### ISSUE THREAD

**Issue by Lockmen** [kangtegong/self-learning-cs#29]
혼공컴운 독자인데 읽기도 쉽고 그림이 많아서 정말 잘 읽고 있습니다.
p311 쪽 멀티스레드 부분을 읽다가 궁금증이 생겨 질문 남깁니다.
멀티스레드에서 스레드마다 레지스터와 스택을 독립적으로 가지고 있는데 왜 이렇게 구성되어 있는걸까요?
인터넷에 검색해보니 이런식으로 설명이 되어 있지만 이해가 안돼서 쉽게 설명해주시면 감사하겠습니다.

스택을 스레드마다 독립적으로 할당하는 이유
스택은 함수 호출 시 전달되는 인자, 작업 후 되돌아갈 주소값 및 함수 내에서 선언하는 변수 등을 저장하기 위해 사용되는 메모리 공간이다.
이에 스택 메모리 공간이 독립적이라는 것은 독립적인 함수 호출이 가능하다는 것이고, 이는 독립적인 실행 흐름이 추가되는 것이다.
스레드의 정의에 따라 독립적인 실행 흐름을 추가하기 위한 최소 조건으로 독립된 스택을 할당한다.

PC Register를 스레드마다 독립적으로 할당하는 이유
PC값은 스레드가 명령어의 어디까지 수행하였는지를 나타내게 된다.
스레드는 CPU를 할당받았다가 스케쥴러에 의해 다시 선점당한다.
그렇기 때문에, 명령어가 연속적으로 수행되지 못하고 어느 부분까지 수행했는지 기억할 필요가 없다.

**Comment by kangtegong** [comment]
말씀하신대로 스택에는 
함수 호출 시 전달되는 인자, 작업 후 되돌아갈 주소값 및 함수 내에서 선언하는 변수 등이 저장됩니다.
스레드는 별도의 작업 흐름이기 때문에 각각의 스레드는 별도의 코드(함수,변수)를 실행할 수 있습니다.
그렇기 때문에 스택을 별도로 할당해주는 것입니다.
프로그램 카운터 (PC)의 경우도 마찬가지입니다.
별도의 실행 흐름을 가지고 있기 때문에 각기 다른 부분의 명령어를 가져와서 실행하게 되겠지요?
그렇기 때문에 스레드마다 별도의 PC값을 가지는 것입니다.
