### ISSUE TITLE
주기억장치와 보조기억장치 외국어 표기에 대한 궁금증

### ISSUE THREAD

**Issue by choi-haram** [kangtegong/self-learning-cs#3]
안녕하세요 책 38쪽을 읽다가 주기억장치와 보조기억장치 외국어 표기에 대해 궁금증이 생겨 질문 드립니다.
주기억장치는 'main memory', 보조기억장치는 'secondary storage'로 표기하신 것을 확인하였습니다.
주기억장치와 보조기억장치 둘 다 기억장치라는 말을 포함하고 있는데 왜 다르게 표기하신지 궁금합니다.

**Comment by kangtegong** [comment]
안녕하세요,
말씀하신대로 둘 다 기억장치라는 점은 동일하나
책에 명시된 표현은 메인 메모리, 보조기억장치를 지칭하는 가장 대중적인 표현을 따른 것입니다.
책에 나와있듯 메모리라는 용어는 보통 메인 메모리를 줄여 부르기 위해 사용되기 때문에
보조기억장치를 지칭할 때는 보통 메모리라는 용어를 잘 쓰지 않기도 합니다.
