### ISSUE TITLE
p. 374 13-1 교착상태 확인문제 1번

### ISSUE THREAD

**Issue by neont21** [kangtegong/self-learning-cs#30]
> 1. 교착 상태에 대한 설명으로 옳은 것을 고르세요.

보기를 아무리 봐도 옳은 것 3개, 옳지 않은 것 1개가 있어
문항이 다음과 같이 수정되어야 하는 것으로 보여 제보 드립니다.

> 1. 교착 상태에 대한 설명으로 옳**지 않**은 것을 고르세요.

**Comment by kangtegong** [comment]
안녕하세요 혹시 1쇄를 보고 계신가요?
해당 부분은 2쇄에서 이미 반영되어 있습니다 :)
그럼에도 제보 감사드립니다.
