### ISSUE TITLE
p136 - 인터럽트 발생시 실행하던 정보를 저장하는 스택에 대해서 궁금합니다.

### ISSUE THREAD

**Issue by this-is-spear** [kangtegong/self-learning-cs#31]
안녕하세요 🙇‍♂️ 
책 읽던 중 궁금증이 생겨 질문드립니다.

<img width="607" alt="스크린샷 2023-02-10 오전 1 10 32" src="https://user-images.githubusercontent.com/92219795/217869606-73051da0-dadb-4e33-a1e5-2e2bdd9f0875.png">

1. 인터럽트가 발생하면 CPU에서 처리 중인 정보가 스택에 저장이 된다고 하셨는데, 말씀하신 스택은 별도로 할당된 메모리 영역인가요? 
2. 만약 별도로 할당된 메모리 영역이라면 운영체제에서 관리하게 된다는 의미인데, 커널에 할당된 메모리 영역에서 관리되는건가요?
3. 인터럽트 서비스 루틴이 실행되면 프로세스가 교체된다고 생각하고 PCB로 저장이 되겠구나 생각을 했는데, 스택이라는 영역을 사용하는 것인거죠?

항상 재미있고 유익하게 읽고 있습니다. 감사합니다 ☺️

**Comment by kangtegong** [comment]
안녕하세요, 좋게 읽어주셔서 감사합니다 :)

1, 2. 별도 할당된 메모리 영역입니다. 커널 영역에서 관리되는 스택이 따로 있습니다.
2. 네 맞습니다 :)
