### ISSUE TITLE
최악 접합 방식의 이점?

### ISSUE THREAD

**Issue by neont21** [kangtegong/self-learning-cs#32]
최초 적합 방식은 검색 시간이 짧다는 이점이 있고
최적 접합 방식은 잉여 공간을 최소화할 수 있다는 이점이 있는데
최악 접합 방식은 어떠한 이점이 있기에 사용하는지 잘 판단이 되지 않아
이 부분에 대한 추가 설명을 해주시면 감사겠습니다.

**Comment by kangtegong** [comment]
최악 적합 방식은 이름과는 달리 외부 단편화를 
(최적적합에 비해) 어느 정도 감소할 수 있는 이점도 있습니다.
가장 빈 공간이 큰 공간에 할당하는 방식이다보니 
아무래도 여분의 빈 공간이 많이 남아 다른 프로세스들을 할당할 수 있는
공간이 남게 되기 때문입니다.
