### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by Bitgochill** [kangtegong/self-learning-cs#35]
안녕하세요! Chapter03| 03-2 명령어의 구조 파트의 간점주소지정방식에 관해 궁금한점이 있습니다. 직접주소지정방식에서 유효주소를 표현할 공간이 작아진다는 단점을 보완하기 위해 간접주소지정방식에서 유효주소의 주소를 사용한다고 하였는데 유효주소의 주소도 결국 메모리에서의 주소이고 유효주소 또한 메모리에서의 주소이라는점에서 차이가 없는것 아닌가요? 감사합니다!

**Comment by kangtegong** [comment]
둘 다 메모리 주소인 것은 맞지만 표현 가능한 범위가 다릅니다.
연산에 사용될 데이터를 저장할 메모리 주소가 어떻게 달라질 수 있는지에 유의해주세요 :) 그렇기 때문에 메모리 참조 횟수에서도 차이가 있습니다.
