### ISSUE TITLE
혼공 컴퓨터구조+운영체제

### ISSUE THREAD

**Issue by cobybriant** [kangtegong/self-learning-cs#38]
선생님 안녕하세요. 컴구조 및 운영체제 공부하고 있는 학생입니다. 선생님 교제를 읽다보니 조금 이해가 안되는 부분이 있어 질문을 하고 싶어 찾아왔습니다. 레지스터 파트 부분에서 프로그램 속 명령어와 데이터는 실행 전후로 반드시 레지스터에 저장됩니다라는 이 문구에서헷갈리는데 실행 전후라는 이 말이 컴퓨터에 있는 모든 프로그램을 저장하고 있다는 내용인지 헷갈립니다. 제가 이 내용을 보고 든 생각은 현재 사용자가 개발하는 프로그램의 실행 전후를 레지스터에 저장한다 또는 실행된 프로그램을 레지스터로 끌고와 저장하고 수정한 내용도 레지스터에 저장된다. 또 궁금한점이 있는데 레지스터도 메모리처럼 컴퓨터가 꺼지면 초기화되는건가요?

**Comment by kangtegong** [comment]
프로그램을 이루는 일부 명령어와 데이터가 레지스터에 저장됩니다.
책에 기술되어 있듯, 레지스터는 그 크기가 메모리보다 작고 현실적으로
모든 프로그램의 명령어와 데이터를 저장할 수 없기 때문입니다.
그리고 수정된 내용이 레지스터에 반영된다면 이 경우 수정된 레지스터 내용이 메모리로 덮어써지게 됩니다.
또한 레지스터도 기본적으로 휘발성이기 때문에 전원이 꺼지면 저장된 내용을 잃게 됩니다.
