### ISSUE TITLE
334쪽 CPU 집중 프로세스와 입출력 집중 프로세스 설명에 대한 질문입니다.

### ISSUE THREAD

**Issue by dlghxo12** [kangtegong/self-learning-cs#39]
334쪽에 CPU 집중 프로세스의 우선순위가 높고 입출력 집중프로세스의 낮다고 되어있고
백그라운드 프로세스의 우선순위가 더 높고 대화형은 우선순위가 낮아도 무방하다 되어있습니다.

앞에 내용에서는 입출력 집중프로세스가 CPU 집중 프로세스보다 먼저 실행된다고 되어있고

인터넷 검색을 해봐도 우선순위가 입출력 집중 프로세스>CPU 집중 프로세스,          대화형 프로세스>백그라운드 프로세스로

되어있어서 (https://rlg1133.tistory.com/96)

뭐가 맞는 설명인지 궁금해서 질문드립니다.

**Comment by kangtegong** [comment]
안녕하세요,
해당 부분은 오타로, 다음 쇄에 수정 반영 예정입니다.
꼼꼼히 읽어주셔서 감사드립니다.

감사합니다.
