### ISSUE TITLE
고립형 입출력(isolated I/O) 주소 공간 관련

### ISSUE THREAD

**Issue by gnsil21** [kangtegong/self-learning-cs#4]
안녕하세요
P243. 고립형 입출력 항목 주소 공간과 관련하여 질문 드립니다.

메모리 맵 입출력의 경우,
입출력장치 접근을 위한 주소공간을 메모리에 할당하여 하나의 주소공간으로 간주하는 것으로 이해하였습니다.
(메모리에 할당하니 당연히 메모리 공간이 축소된다는 흐름까지 이해)

고립형 입출력의 경우,
주소 공간을 분리한다고 하시며 예시에 들어 1024개(예시)의 주소 공간을 활용할 수 있다고 언급되었습니다.
이해가 되지 않는 점은 이 점입니다.
저기에 언급된 입출력장치의 주소공간은 어디에 위치하는지 궁금하여 질문 드립니다.
일단 주소를 알고 있다면, CPU는 '입출력장치 읽기/쓰기 선'을 통해 장치 컨트롤러에 접근하는 점은 이해되는데
1024개(예시)나 되는 입출력장치의 주소공간은 어디에 있고 
CPU가 어떻게 읽고 입출력장치에 접근하는지 이해가 되지 않아 문의드립니다.
(입출력장치별로 '읽기/쓰기 선'을 가진다? 그래서 CPU가 입출력장치를 개별적으로 인식해서 처리한다?
 쉬이 머릿속에 와닿지 않아 글을 남기게 되었습니다.)

번잡한 글 읽어 주셔서 감사합니다.

**Comment by kangtegong** [comment]
안녕하세요
질문 감사합니다
(추후 입출력장치 파트 뒷부분에 나오지만)
입출력장치 내부에도 RAM(메모리)가 있습니다.
사실 최신 입출력장치의 경우 많은 경우 메모리를 탑재하고 있지요.
고립형 입출력의 경우 이런 것들을 활용합니다.
