### ISSUE TITLE
p420 논리주소 그림 좌우 바뀜

### ISSUE THREAD

**Issue by happineer** [kangtegong/self-learning-cs#41]
p420 에서 계층적 페이지 설명할때, 
계층적 페이징을 사용하지 않는 경우의 논리주소 구조그림이 p410의 그림과 좌/우가 바뀌어 있습니다.

**Comment by kangtegong** [comment]
안녕하세요,
꼼꼼히 읽어주셔서 진심으로 감사드립니다.

참고로, CPU/운영체제/비트를 읽는 순서에 따라 달라질 수 있고
그렇기에 전공 서적마다 논리주소를 표기하는 방법이 다릅니다.
(그래서 비트 순서열을 표기하지 않은 것입니다)
논리 주소가 페이지 번호와 변위로 이루어져 있다는 점만 이해하시면 되는 부분이기 때문에
다음 쇄에 보고해주신 내용이 반영되지 않을 수 있습니다.

그럼에도 다시 한 번 꼼꼼히 읽어주셔서 감사드립니다.
