### ISSUE TITLE
p407 오타수정

### ISSUE THREAD

**Issue by happineer** [kangtegong/self-learning-cs#43]
p407 하단에 페이지 테이블을 설명하는 문장 하나가 고쳐져야 할것 같습니다.

원문: "프로세스마다 각자의 **프로세스 테이블**을 가지고 있고 각 프로세스의 페이지 테이블들은 메모리에 적재되어 있습니다."
수정: "프로세스마다 각자의 **페이지 테이블**을 가지고 있고 각 프로세스의 페이지 테이블들은 메모리에 적재되어 있습니다."

**Comment by kangtegong** [comment]
꼼꼼히 읽어주셔서 감사합니다. 다음 쇄에 반영하도록 하겠습니다.

감사합니다.
