### ISSUE TITLE
혼공운체 27강 프로세스 상태와 계층 구조 질문 

### ISSUE THREAD

**Issue by minsurim** [kangtegong/self-learning-cs#44]
프로세스 생성할 때 fork랑 exec해서 자식 프로세스가 만들어지는거 잖아요. 근데 fork해서 복제하고, exec해서 코드 영역이랑 데이터 영역의 내용은 바뀌고 나머지는 초기화 되면, 부모 프로세스랑 자식 프로세스의 유사점? 부모프로세스의 흔적? 이런건 없나요?

**Comment by kangtegong** [comment]
유사점이나 흔적 등은 그 의미가 모호하여 잘 모르겠으나,
PID와 PPID로서의 구분이 가능합니다.
그리고 페이징을 설명할 때 다루었던 
쓰기시 복사도 참고해보세요 :)
