### ISSUE TITLE
컴파일언어와 인터프리터언어 질문 (85page)

### ISSUE THREAD

**Issue by looloolang** [kangtegong/self-learning-cs#48]
컴파일 언어가 인터프리터 언어보다 빠르다고 설명되어있습니다.

컴파일 언어의 경우, 전체코드를 목적코드로 컴파일 + 목적코드를 실행 하는 것이고
인터프리터 언어의 경우, 한줄 단위로 저급언어로 해석 & 실행 한다고 하셨는데

제가 느끼기에는 컴파일 언어랑 인터프리터 언어 둘다 '저급언어로 해석+실행' 시키는 관점에서는 수행 단위가 다를뿐 시간은 비슷할것 같다고 느껴집니다.

어떤 부분에서 컴파일 언어가 인터프리터 언어보다 빠른것인지 설명 부탁드립니다.

**Comment by kangtegong** [comment]
컴파일 언어와 인터프리터 언어를 각각 '실행한다'는 의미를 되새겨볼 필요가 있습니다.
컴파일 언어를 실행한다는 것은 '저급언어로 변환된' 코드를 실행한다는 의미이고
인터프리터 언어를 실행한다는 것은 고급 언어를 해석 & 실행을 동시에 하는 것입니다.
그래서 전자가 빠른 것입니다.
