### ISSUE TITLE
클럭과 워드 등에 관하여 질문있습니다.(질문 3개)

### ISSUE THREAD

**Issue by chlahfo** [kangtegong/self-learning-cs#49]
1. 클럭은 컴퓨터 부품의 박자같은거고, 워드는 CPU가 한번에 처리할 수 있는 데이터의 단위라고 나와있는데.. 1클럭당 최대 1워드씩 실행되는건가요?? 

2. 1클럭 안에서도 여러 개의 명령어나 데이터도 실행될 수 있는건가요?? 한 개의 명령어나 데이터 이동도 여러 클럭이 걸릴 수 있다는 것은 알겠는데, 그 반대의 경우도 가능한 것인지 궁금합니다.

3. 혹시 명령어의 길이는 CPU 의 1워드만큼씩 잘리나요?? 
주소지정방식에서 간접주소지정 방식을 사용하는 이유에서 명령어의 길이가 제한되었을 때 데이터의 표현 길이가 제한되기 때문이라고 들었는데요. 특히 전의 질문드렸을 때 [큰 데이터의 경우 내부적으로는 한정된 크기의 단위로 잘려서 메모리에 저장됩니다. ] 라고 답변 주셨었습니다. 그래서 궁금해진 것인데, 그 잘리는 단위가 1워드 인지 궁금합니다.
전에 관련이 없을 것 같았던 메모리의 포인터 변수의 크기도 CPU 1워드 값과 같다고 알게 되어서 혹시나해서 여쭤봅니다.(참고 사이트: http://www.tcpschool.com/c/c_pointer_intro)

**Comment by kangtegong** [comment]
1. 일반적으로 그렇습니다.
2. 한 클럭 안에 여러 명령어가 실행될 수도 있습니다. 책의 [CPU 성능 향상 기법] 항목의 슈퍼스칼라 부분을 참고해보세요.
3. 네, 명령어/데이터는 기본적으로 1워드를 넘기지 않기 때문입니다. 만일 그보다 큰 데이터의 경우 여러 주소에 걸쳐 저장됩니다 :)
