### ISSUE TITLE
같은 x86-64 임에도 어셈블리어가 다른 이유가 궁금합니다?

### ISSUE THREAD

**Issue by richyoo** [kangtegong/self-learning-cs#5]
안녕하세요!
책과 유튜브를 열심히 보는 독자입니다.

godbolt.org에서
같은 x86-64임에도 gcc 버전 4.1.2에선
  레지스터 앞에 %가 붙고
 다른 gcc 12.5버전은 %가 안붙는 이유가 무엇인지요?
( 예. push %rbp 와 push rbp)

결국 어셈블리어는 기계어와 일대일 매칭이 되어야
하는 것이 아닌가요? 그렇다면 고급언어를 컴파일한
어셈블리는 같아야하는 것이 아닌가 하는 질문 드립니다
초보적인 질문이라 죄송합니다.

**Comment by kangtegong** [comment]
안녕하세요. 반갑습니다.
단순 표기법의 차이로 보입니다.

가령 같은 x86 어셈블리어라도 intel 문법 체계로 표기할 수 있고
AT&T 문법 체계로 표기할 수 있습니다.

Intel 문법을 따르는 어셈블리어에서는 
`mov eax, 1`

AT&T 문법을 따르는 어셈블리어에서는
`movl #1, %eax`
로 표기합니다.

참고로, 강의와 책에서 언급했듯 같은 아키텍처라도 (같은 x86이라도) 컴파일러 종류에 따라서도 
생성되는 어셈블리어는 달라질 수 있습니다. 
가령
