### ISSUE TITLE
C언어에서의 함수 return 명령어와 어셈블리어의 Return 은 다른 개념인가요??

### ISSUE THREAD

**Issue by chlahfo** [kangtegong/self-learning-cs#50]
같은 개념인지 아니면 C언어 등에서의 return 명령어가 어셈블리어 Return 명령어와 다른 명령어를 포함해서 만들어진 개념인지 궁금합니다.

함수가 종료되면 Return 명령어가 쓰인다는 점에서는 같고, C언어도 Return 명령어를 쓰면 함수를 종료 하고 다시 원래 있던 곳으로 돌아간다는 점에서 같은 거 같기도 같기도 합니다만...C언어에서 return 은 값을 반환하는 동작이 포함되어있잖아요.
반면 어셈블리어는 배워본 적은 없지만, 왠지 혼공컴운에서 RETURN 명령어 설명에 값 반환 얘기가 안쓰여있는거보니 함수 값 반환하는 명령어는 따로 있는거같아서요.

**Comment by kangtegong** [comment]
어셈블리어에 따라 ret 등으로 표기되기도 하는데, 거의 같은 의미입니다.
단지 어셈블리어에서는 loop을 형성한 label 등으로 되돌아가라는 의미로 사용되는 경우가 많습니다.
반환값이 없는 경우가 많지요.
어셈블리어 자체를 학습해보시는 것도 좋은 방법일 듯 합니다.
말씀하신대로 처음 학습할 때에는 어려울 수 있지만
천천히 읽다보면 쉽게 쓰여져 있는 문서들도 많습니다.
하나하나 모두 기억하려하기보다는 큰 흐름만 기억한다는 생각으로 학습해보시기 바랍니다.
 
https://blog.ksc.re.kr/244

이해가 어려우시다면 하단 링크에서 C언어가 어셈블리어로 어떻게 변환되는지 관찰해보는 것도 좋습니다.

https://godbolt.org/

**Comment by chlahfo** [comment]
진짜 제 삶의 빛... ㅠㅠ 감사합니다

**Comment by chlahfo** [comment]
와..감사합니다!!
