### ISSUE TITLE
인터럽트 벡터 데이터 버스를 타는 이유 중에서

### ISSUE THREAD

**Issue by chlahfo** [kangtegong/self-learning-cs#51]
1. 아무리 찾아봐도...
인터럽트 벡터는 인터럽트 서비스 루틴(ISR)의 시작 주소를 담고있으며, 인터럽트 벡터 테이블은 인터럽트 발생시 처리해야 할 루틴의 주소를 보관하고 있는 테이블이다.(==인터럽트 벡터들이 저장되어있는 테이블)라는 얘기밖에 없는데.. 
인터럽트 벡터가 가지고 있는 데이터는 루틴의 시작 주소 외에 어떤 것이 있나요..? 

2. 혹시 간접 주소 지정 방식처럼 인터럽트 벡터 테이블 위치를 담고있나요?? 근데 그것도 마찬가지로 주소를 담고있는거니까 주소버스를 타야할거같은데..

3. 또 인터럽트 벡터가 ISR의 시작 주소 외에 데이터를 가지고 있다고 치더라도, 시작 주소를 가진 것은 맞는데.. 해당 정보를 나눠서 데이터 버스와 주소버스를 따로 타지 않는 이유가 무엇인가요??

**Comment by kangtegong** [comment]
인터럽트 유형, 인터럽트 우선순위, 인터럽트 처리 상태 등이 함께 있을 수 있습니다.
물론 어떤 정보가 있는지는 시스템마다 차이가 있을 수는 있습니다.
시작 주소는 인터럽트 벡터 테이블 관점에서 보면 인럽럽트 벡터의 중요한 정보일 수는 있지만
그것이 유일한 정보는 아니기에 데이터버스를 타는 것이 아닐까 짐작해봅니다.
(설계의 의도까지 이해하려면 특정 제품군의 메뉴얼을 보아야 할 수 있을 듯 합니다.)

**Comment by chlahfo** [comment]
아하 감사합니다
