### ISSUE TITLE
레지스터 질문 (4-2강)

### ISSUE THREAD

**Issue by looloolang** [kangtegong/self-learning-cs#52]
1. 프로그램 카운터는 메모리에서 읽어들일 명령어의 주소를 저장한다고 되어있습니다.

메모리에는 데이터와 명령어가 0과 1의 형태로 저장되어있을텐데 읽어들이고자 하는 것이 데이터인지 명령어인지 어떻게 구분하는지에 대해 의문이 생겼습니다.
(제 짧은 생각으로는 데이터는 명령어 없이는 의미없는 존재이므로 하나의 주소에 데이터와 명령어가 항상 같이 저장되어 있을 것 같다는 생각이 드는데.. 답변 부탁드립니다ㅠ)

2. 프로그램 카운터랑 메모리 주소 레지스터랑 보면 거의 같은 값을 가지고 뭔가 목적이 메모리의 주소가 저장된다는 관점에서 같아보이는데, 이둘이 분류되어있는 이유가 궁금합니다.
메모리 주소 레지스터에는 데이터의 주소도 저장될수있고 명령어의 주소도 저장될수있어서 분류한건가요?

3.114page 예시에서 '이해를 돕기위해 프로그램을 이루는 명령어들은 각각 하나의 메모리 번지를 차지하고 있다고 가정' 이렇게 명시되어있습니다.
메모리 안에는 1101, 1111, 1000 데이터가 저장되어있고 그림상으로 보이지 않는 곳에 명령어가 각 번지수마다 있다는 의미인건가요?

일반적으로 각 번지마다 명령어가 다 존재하나요?

4.116페이지 04 단계에서 제어장치에 명령어레지스터를 통해 명령어가 input으로 안들어갔는데 read라는 제어신호가 나온것은, 프로그램 첫 실행(?) 에대한 제이장치의 디폴트 설정이라고 보면될까요?

**Comment by kangtegong** [comment]
1. 크게 구분짓지 않습니다. 어떻게 해석하느냐에 따라 다릅니다. CPU가 이해할 수 있는 명령 코드로 이루어져 있고 그것이 코드 영역에 존재한다면 (프로세스와 스레드 장을 참고해주세요) 명령어인 것입니다. 
2. 같은 주소를 저장할 수 있어도, 프로그램 카운터는 '언제나 다음 실행할 주소'를 저장한다는 점에서 차이가 있습니다.
3. 그렇습니다. 정확하게는 1번에서 언급해드렸던 코드 영역에 명령어가 존재합니다.
4. 네, 그에 대한 상세한 원리는 의도적으로 기술하지 않았습니다. 그렇게 생각하셔도 문제는 없을 것입니다.
