### ISSUE TITLE
303p 예제 코드 fork 함수가 오류 납니다 추가로 설치해야 할 것이 있을까요?

### ISSUE THREAD

**Issue by chlahfo** [kangtegong/self-learning-cs#53]
#include <unistd.h>를 해서인지 getpid()도 정상적으로 출력하였는데 fork 함수에서 오류가 나서 컴파일이 불가능하네요.. 혹시 추가로 설치해야 할 파일이 있을까요?

(환경 : window 10, vs code, gcc compiler 사용 중)
(오류 메세지 : implicit declaration of function 'fork'[-Wimplicit-function-declaration])

**Comment by chlahfo** [comment]
일단 여기까지 썼었습니다

#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>

int main(){
    printf("hello, os\n");
    printf("my pid is %d", getpid());

    if (fork() == 0){ //여기서 오류
        printf("child pid is %d\n", getpid());
    }
    return 0;
}

**Comment by kangtegong** [comment]
작성하신 코드에는 문제가 없어 보이지만
Windows 상의 gcc 컴파일러에서 지원되지 않는 것으로 보입니다.

https://stackoverflow.com/a/9612414

참고로, 책에서 대부분의 운영체제는 fork-exec으로 실행된다고 서술했고 실제로도 그러하지만
한 가지 예외가 되는 운영체제가 바로 Windows입니다.
Windows에선 fork-exec으로 실행되는 것이 아닌
아래와 같은 별도의 과정이 사용됩니다.

https://learn.microsoft.com/ko-kr/windows/win32/procthread/creating-processes

**Comment by chlahfo** [comment]
헐... ㄱ감사합니다...
