### ISSUE TITLE
강의 슬라이드 문의

### ISSUE THREAD

**Issue by g471000** [kangtegong/self-learning-cs#54]
안녕하세요!

스터디 모임에서 이 책을 이용해서 스터디 모임 진행하려고 하는데요, 한명씩 돌아가면서 강의하는 식으로 하려고 해요.
그래서, 선생님께서 강의에서 쓰신 슬라이드를 혹시 어디선가 엑세스 할 수 있을까요? 아니면 공개용이 아닐까요?

좋은 책 출판해주셔서 정말 감사합니다!

**Comment by kangtegong** [comment]
안녕하세요, 좋게 읽어주셔서 감사합니다 :)
강의 슬라이드의 경우 공개용은 아닙니다..ㅠㅠ


감사합니다.
강민철 드림
