### ISSUE TITLE
[질문] 블로그에 책 요약한 내용을 공유해도 되나요 ?

### ISSUE THREAD

**Issue by rriver2** [kangtegong/self-learning-cs#55]
안녕하세요 :) 혼공컴운으로 공부중인 학생입니다.
유튜브 강의 수강 및 책을 읽으면서 책 내용을 정리했는데, 주변에서 공유해줬으면 좋겠다는 의견이 있어서 블로그에 요약 노트를 올리고자 하는데,
저작권 이슈가 있을 것 같아서 블로그에 책 요약한 내용을 공유해도 되는지 질문 드리러 왔습니다.

당연히 블로그 글 및 요약 노트에는 책 출처를 남길 예정이고, 요약한 노트 예시는 다음과 같습니다 ! 

유익한 내용으로 설명해주셔서 감사합니다. 제 답답했던 운체 공부의 빛이십니다... ✨

![혼자 공부하는 컴퓨터 구조 + 운영체제-5](https://user-images.githubusercontent.com/82457928/232648187-9e058518-93cb-4ac5-af37-0102988a8b98.jpg)

**Comment by kangtegong** [comment]
와우 정말 너무 잘 정리하시네요.. 대단하십니다.
네, 출처만 남겨주신다면 얼마든지 가능합니다 :)
좋게 읽어주셔서 감사드립니다.

**Comment by rriver2** [comment]
넵 감사합니다 !! 
[블로그 링크](https://rriver2.tistory.com/entry/%ED%98%BC%EC%9E%90-%EA%B3%B5%EB%B6%80%ED%95%98%EB%8A%94-%EC%BB%B4%ED%93%A8%ED%84%B0-%EA%B5%AC%EC%A1%B0-%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%9A%94%EC%95%BD-%EC%BB%B4%ED%93%A8%ED%84%B0-%EA%B5%AC%EC%A1%B0-%ED%8E%B8) 보시고 혹시 문제 있으면 연락주세요 :)
