### ISSUE TITLE
교재 내용 질문

### ISSUE THREAD

**Issue by steveN0216** [kangtegong/self-learning-cs#56]
60 페이지에 2의 보수 표현의 한계에 관해 질문이 있습니다.

제가 알기론, 0은 양수도 음수도 아니여서 음수처리 같은 것이 아예 불가능한 걸로 알고 있는데, “0의 이진수에 2의 보수를 취하면 … 원하는 음수값을 얻을 수 없습니다.” 라는 문장이 본질적으로 무엇을 말씀하시고자 하는지 이해가 안됩니다. 2의 보수를 취하는 이유는 이진수 상태에서 음수로 표현하기 위함인데 이걸 왜 0에 하는지 모르겠습니다.
또한 2의 n제곱 형태의 이진수에 2의 보수를 취하면, 음수 값의 이진수가 양수 값의 이진수와 같게 되어버리는 문제가 생긴다고 하셨는데 저는 이것이 왜 문제인지 모르겠습니다. 설령 음수와 양수의 이진수 값이 같다할지라도 플래그로 음수인지 양수인지 표현하면 해결되는 문제 아닌가요? 부호 플래그가 특정 이진수를 음수로 표현한 값이 다른 이진수(양수)와 같을 때 이를 구별해주는 역할을 하는데, 여기서도 똑같이 그 역할을 하면 되지 않나 싶습니다.

**Comment by kangtegong** [comment]
사람 입장에서는 0이 양수도 음수도 아니라는 것을 알 수 있으나,
컴퓨터 입장에서 생각했을 때, 0으로만 이루어진 비트열(0)도 다른 여타 비트열과 동일하게 간주합니다.
그때 0으로만 이루어진 비트열을 2의 보수로 표현할 때 문제가 생길 수 있음을 나타내는 문장입니다.

또한 2의 제곱의 경우 그렇게 되면 다른 수와의 연산 과정에서 영향이 있을 수 있습니다
다른 연산은 부호 플래그와 관련 없이 연산 결과가 도출됩니다.
예를 들어, -3을 나타낸 2의 보수와 1을 더하면
-2를 나타낸 2의 보수가 나옵니다.
다만 2의 제곱의 경우 그러한 연산이 어렵습니다.

**Comment by steveN0216** [comment]
살짝 지엽적인 느낌이 들긴 하지만, 2의 제곱의 형태의 2의 보수에 관해 조금 더 자세히 설명 부탁드립니다.
다른 연산은 부호 플래그와 관련 없이 연산 결과가 도출된다는 것이 무슨 말씀이신가요? 이해가 안됩니다..

**Comment by kangtegong** [comment]
-3과 5를 더하는 연산을 생각해보세요
-3은 2의 보수로 1101입니다. 
5는 1001입니다. 
이 둘을 더한 결과는 0010입니다.
이는 2입니다.

반면, -4(-2^2)와 4(2^2)는 2의 보수 본래의 수가 모두 같은 수가 됩니다. 
이 둘을 5와 더한다고 해도 
결과가 1인지 9인지 알기 어렵습니다.
