### ISSUE TITLE
간접 주소 지정 방식 질문

### ISSUE THREAD

**Issue by steveN0216** [kangtegong/self-learning-cs#57]
간접 주소 지정 방식의 이점이 무엇인지 모르겠습니다. 메모리에 유효 주소를 명시해서 직접 주소 지정 방식보다 표현 가능한 범위가 넓어졌다는 건 이해가 갑니다만, 유효 주소의 주소를 오퍼랜드 필드에 명시해야 한다는 점에 있어 결국 똑같지 않나 싶습니다. 예를 들어, 직접 주소 지정 방식으로 유효 주소를 메모리 10번지 명시한 경우와 간접 주소 지정 방식으로 유효 주소를 메모리 9번지에 그리고 유효 주소의 주소를 메모리 10번지에 명시한다면, 유효 주소나 유효 주소의 주소나의 차이만 있을 뿐 표현 가능한 범위는 똑같지 않나요?

**Comment by kangtegong** [comment]
하단에 유사한 질문에 대한 답을 작성해드렸습니다. 참고해보시면 좋을 것 같습니다 :)

https://github.com/kangtegong/self-learning-cs/issues/10

https://github.com/kangtegong/self-learning-cs/issues/26
