### ISSUE TITLE
P67 문자 인코딩 질문

### ISSUE THREAD

**Issue by steveN0216** [kangtegong/self-learning-cs#59]
같은 문자 집합에 대해서 다양한 인코딩 방식이 존재함으로써 얻는 이점은 무엇인가요?

유니코드를 예를 들자면, 유니코드 문자 집합에서는 각 문자마다 고유한 값이 부여된다고 하는데 그럼 왜 여러 인코딩 방식을 가지는지 궁금합니다. 아스키 코드처럼 글자 각각에 부여된 값을 인코딩 값으로 삼아도 괜찮지 않나요?

**Comment by kangtegong** [comment]
안녕하세요, 

관련하여 찾아본 결과 
유니코드는 각국의 언어별 인코딩을 지원하는데,
많은 비트를 할애하는 언어의 인코딩과 그렇지 않은 인코딩을 구분하기 위해
다양한 인코딩을 지원하는 것이 주된 이유인듯 합니다.

가령 8bit ASCII로 표현할 수 있는 알파벳의 경우 굳이 긴 인코딩은 필요하지 않고
같은 문자집합을 공유하더라도 다른 언어와 구분되어 인코딩되는 것이 바람직할 것입니다.
(그래서 주로 ASCII-compatible한 UTF-8이 대중적으로 이용됩니다)

https://softwareengineering.stackexchange.com/questions/77758/why-are-there-multiple-unicode-encodings
https://javarevisited.blogspot.com/2015/02/difference-between-utf-8-utf-16-and-utf.html#axzz85xJEtwev
