### ISSUE TITLE
이중 모드 관련 질문 드립니다.

### ISSUE THREAD

**Issue by gnsil21** [kangtegong/self-learning-cs#6]
안녕하세요. 

일전 문의에 대한 답변 감사합니다. 
스스로 어려워 하던 게 바보스러웠을 정도로 간단 명료하게 이해할 수 있는 답변이었습니다.

오늘은 p271의 운영체제 이중모드와 관련하여 질문 드립니다.

1. 이중 모드 구현 이유 
본문에서는 자원 접근을 제어하기 위해 이중 모드로 구분한 것으로 이해하였습니다.
그런데 응용 프로그램이 빈번하게 모드 전환이 이루어진다는 내용을 보며
'왜?' 이중 모드를 구현 했을까라는 의문이 들었습니다.
시스템 호출하면 커널모드로 전환되어 자원 이용이 가능해 보여서
애초에 단일 모드로도 가능하지 않을까하는 생각도 들었습니다.
당연히 이중 모드로 구분한 이유가 있을 것 같은데 제가 이해를 제대로 한 것 같지 않아 문의드립니다.

2. 이중 모드 = 운영체제 계정 권한?
운영체제의 사용자 계정 권한(사용자 계정과 관리자(root) 계정으로 구분된 형태) 체계를
이중 모드의 구현으로 보면 되는것인지 궁금합니다.
윈도우에서도 일부 시스템의 경우,
[관리자 권한으로 실행]이라는 옵션값으로 실행해야 특정 명령어나 디렉터리 접근이 가능한 경우가 있어
다른 것 같으면서도 '혹시 같은게 아닐까'라는 생각이 들어 문의드리게 되었습니다.

사실 책을 읽으며
이렇게 질문을 할 수 있게 되었다는게 
'내용을 읽을 수 있게 되었다.'라는 감상이 들어 만족스럽습니다.

질문 글을 빌어 감사하다는 말씀 드리고 싶습니다.

**Comment by kangtegong** [comment]
1. 여러 가지 이유가 있지만 대표적인 이유를 설명드리자면, 코드의 재사용성 때문에 그렇습니다.

이중 모드로서 커널을 사용하는 로직(커널의 소스코드라고 생각해도 좋습니다)는 여러 사용자 영역의 프로그램이 공통적으로 사용할 수 있습니다.
가령 파일에 접근하는 동작은 커널 모드로만 동작을 하는데, 파일에 접근하는 프로그램은 여러 프로그램이 있을 수 있습니다. 웹 브라우저, 게임, 워드프로세서 등등이요. 이중모드를 통해 커널의 코드를 실행하도록 하면 이 각각의 프로그램들이 파일에 접근할때 각자 프로그램 내에 '파일에 접근하는 코드'를 넣을 필요 없이 운영체제 내의 코드로서 공통적으로 파일에 접근할 수 있습니다. 사용자 프로그램에 일일이 자원에 접근하고 이용하는 코드를 넣을 필요가 없어지게 되는 것이지요.

2. 비슷하지만 조금 다릅니다. 물론 root계정으로는 일반 사용자 계정보다 실행할 수 있는 코드의 종류가 조금 더 다양해지는것은 사실이나, 사용자 모드도 커널 영역을 실행할 수 있고 root 계정도 사용자 영역의 코드를 실행할 수 있거든요. 

좋게 읽어주셔서 감사드립니다^^
그리고 좋은 질문 감사드립니다.
