### ISSUE TITLE
유튜브 강의 내용 작성에 관하여 문의 드립니다.

### ISSUE THREAD

**Issue by jeongwon-choi** [kangtegong/self-learning-cs#64]
안녕하세요~

컴퓨터 기본 지식이 부족하다 보니 너무 답답해서 서칭하다가

현재 혼자 공부하는 컴퓨터구조+운영체제 교재를 구매하여 유튜브 강의를 듣고 있습니다.

유튜브 강의를 듣고 해당 내용을 블로그에 기록을 해보려고 하는데요. 

작성하고 보니 문제가 될 수도 있을 부분으로 생각이 들어 현재는 글을 모두 내려두었습니다.

먼저 생각 없이 글을 작성했던 부분 사과드리겠습니다.

해당 부분 허락해 주시면 글로 남겨보고 싶습니다.

**Comment by kangtegong** [comment]
안녕하세요^^ 출처만 명시해주신다면 자유로이 정리해주셔도 모방합니다. 오히려 저로서는 감사한 일입니다. 
꼼꼼히 읽어주셔서 진심으로 감사드립니다.

**Comment by jeongwon-choi** [comment]
허락해 주셔서 정말 감사합니다~
제공해주신 좋은 강의 들으면서 기초부터 차근차근 다지도록 하겠습니다.
