### ISSUE TITLE
운영체제가 돌아가고 있을 때 CPU 모드는 커널모드인건가요?

### ISSUE THREAD

**Issue by kontikiki** [kangtegong/self-learning-cs#66]
질문이 있습니다. 
운영체제가 커널영역에 적재된 프로그램이라고 했는데요, 이 운영체제 프로세스가 돌아가고 있을 때엔 CPU가 커널모드로 실행되고 있는거라고 이해하면 될까요? 
그리고 만약에 (일반적인)프로세스가 실행상태라면, CPU는 사용자모드라고 보면 될까요?
말하자면 스케줄링 작업이 발생할 때마다 커널모드로 전환되어 운영체제가 일하고서 다시 사용자 모드로 전환되어 프로세스가 실행되는.. 그런식이라고 이해하면 될까요?

**Comment by kangtegong** [comment]
운영체제 코드가 항시 돌아갈 경우에는 커널 모드가 맞습니다만
많은 경우 운영체제를 실행하는 주체는 결국 사용자 영역의 프로세스입니다.
그렇기에 말씀해주신 것처럼 
스케줄링 작업이 발생할 때마다 커널모드로 전환되어 운영체제가 일하고서 다시 사용자 모드로 전환되어 프로세스가 실행되는 방식으로
실행됩니다 :)
