### ISSUE TITLE
자식 프로세스 관련

### ISSUE THREAD

**Issue by CheorHyeon** [kangtegong/self-learning-cs#67]
안녕하세요 궁금한 점이 생겨 질문 드리고자 합니다.

1. 자식 프로세스는 부모 프로세스의 자원을 그대로 받는데, 사실 이게 exec 명령어로 프로그램을 바꿔주는거면 결국에는 **별도의 프로세스를 따로 두는 것과 다를 것이 없는 것** 같은데, 보통의 OS에서 계층적 구조를 꼭 이뤄야 하도록 설계가 되어있나요? 
제가 뭔가 다른 점이 직접적으로 와닿지가 않는 것 같습니다 ㅜㅜ
-> **어떤 로직 같은 경우에는 순차적 실행이 되야하니 필요한건지** 궁금합니다.

제가 괜히 조금 깊게 생각을 하는 것 같긴 한데.. 궁금하여 질문 남겨드립니다! 답변 주시면 감사하겠습니다!

**Comment by kangtegong** [comment]
안녕하세요, exec 명령어는 단순히 "현재 메모리 공간을 다른 프로그램으로 덮어쓰라"는 명령어 입니다.
즉, exec 전에 자식 프로세스의 메모리 공간이 확보되었다는 전제가 있어야 exec이 제대로 동작하는 것이지요 :)

그리고 계층적으로 프로세스를 관리해야 부모 프로세스가 자식 프로세스의 자원을 올바르게 회수하고 종료를 처리할 수 있습니다.
자식 프로세스(들)가 실행을 끝낸다면, 그 사실을 부모 프로세스가 알아야 합니다.
다시 말해 부모 프로세스가 자식 프로세스가 종료되었다고 처리를 해주어야 하지요.
(관련해서 wait 시스템 콜을 찾아보시면 도움이 되실 겁니다 ^^)

이걸 하지 않으면 자식 프로세스는 종료가 되었음에도 제대로 종료가 처리되지 않아 
커널이 관리하는 프로세스 목록에 남아있는 상태가 됩니다.
이걸 '좀비 프로세스(zombie process)'라 부릅니다.

이런 이유에서 많은 운영체제는 fork-exec 기반의 계층적 프로세스 관리를 하는 것입니다.
자식 프로세스가 부모 프로세스로부터 쉽게 생성될 수 있도록 하고,
부모 프로세스는 자식 프로세스의 실행-종료를 일괄적으로 처리해줄 수 있기 때문입니다.
