### ISSUE TITLE
p.182 Sdram 질문있습니다.

### ISSUE THREAD

**Issue by developer-wonjin** [kangtegong/self-learning-cs#7]
SDRAM 앞서 DRAM을 설명할 때 클럭신호에 대한 설명이 없었는데요.
SDRAM이 클럭신호와 동기화 되었다는 설명을 통해
DRAM은 클럭신호와 동기화되지 않은 장치라고 유추해볼 수 있을것  같습니다.

하지만, 컴퓨터 장치들은 클럭신호라는 박자에 맞춰서 일사분란하게 작동한다고 p.108에 설명해주셨던 개념과 혼동이 됩니다.

DRAM과 클럭신호간의 관계를 어떻게 정리할 수 있는지 궁금합니다.

**Comment by kangtegong** [comment]
"컴퓨터 장치들은 클럭신호라는 박자에 맞춰서 일사분란하게 작동한다"
라는 말은 컴퓨터에 연결되어 있는 모든 장치들을 의미하지는 않습니다.

가령 컴퓨터 외부에 연결되는 입출력장치의 경우 
클록 신호와 동기화되어 있지 않은 경우도 많습니다.
그 경우 인터럽트, 폴링이나 (혹시 이후의 부분도 읽어주셨을지는 모르겠으나) DMA 등을 이용하게 되지요.
클록 신호와 동기화되지 않은 DRAM도 마찬가지 맥락입니다.
클록신호와 동기화되어 있지 않은 DRAM을 의미합니다.

다만 최근 많은 부품들은 클록 신호와 동기화되도록 설계되어 있기에 
"클록신호는 컴퓨터의 부품들의 박자다"라고 이해하셔도 큰 무리는 없습니다.
DRAM 또한 책에서 언급되었듯 현재 가장 대중적으로 사용되는 하드웨어는 클록신호와 동기화된 DDRn SDRAM입니다.
