### ISSUE TITLE
190p 메모리 보호 기법 질문

### ISSUE THREAD

**Issue by DRTIKIM** [kangtegong/self-learning-cs#70]
190p의 '1500번지에 숫자 100을 저장하라'와 같은 명령이 실행 되서는 안되는 이유는 뭔가요??

메모장의 물리 주소가 1000~ 1999 번지 라면 메모장 물리구조 1500번지에 숫자 100을 저장 할 수 있는 것 아닌가요?? 

갑자기 메모장의 논리주소가 0~999번지로 나타나는 이유가 뭔가요 ?? 

191 p의 '프로 그램의 논리 주소 영역을 벗어 났기 때문에 명령어가 실행되어서는 안된다' 라는게 이해가 안됩니다 ㅠ

**Comment by kangtegong** [comment]
안녕하세요!

"1500번지에 숫자 100을 저장하라"라는 명령어에서  1500번지는 물리주소가 아닌 논리주소입니다

아마 이 1500번지를 물리 주소라고 혼동하신 것이 아닐까 싶습니다 :)

책에서 설명드렸듯 CPU는 물리 주소를 이해하지 않습니다.

1500번지를 실행하라고 해 봤자 0번지부터 999번지까지인 메모장의 주소 공간을 벗어나기 때문에 실행되어선 안됩니다.
