### ISSUE TITLE
페이지 85쪽에서 질문이 있습니다.

### ISSUE THREAD

**Issue by spidychoi** [kangtegong/self-learning-cs#72]
파이썬이 인터프리터 언어여서 오류가 N번째 줄이 있으면 그전에 줄인 N-1줄까지는 실행된다고 하셨습니다. 그부분은 이해가 됬는데, 이런 질문이 들었습니다. 가끔 GUI앱을 파이썬으로 만들면 작동은 다됩니다. 근데 앱을 종료하고 나면 오류가 그떄 출력하는 경우들이 있습니다. 그럼 이것이 어떻게 85쪽에서 설명하신 원리와 부합하는지 알고 싶습니다.(어떻게 앱이 돌아가고 종료된뒤 오료가 보이는지 자세한 설명 부탁 드립니다). 좋은책 내주셔서 감사 합니다.

**Comment by kangtegong** [comment]
안녕하세요..!
정확한 오류 메세지를 알기는 어려우나
짐작해보건대 실시간으로 생성되는 오류 메세지를 버퍼 등에 저장했다가
종료시 한 번에 출력하는 것일 수도 있고

아니면 종류 과정 자체에 문제가 있는 것일 수도 있습니다 :)

감사합니다
