### ISSUE TITLE
어떤 원리인지 알고 싶습니다.

### ISSUE THREAD

**Issue by spidychoipro** [kangtegong/self-learning-cs#74]
(아까 올린거는 실수로 올라 갔네요 죄송합니다)

167쪽에 보면은  인텔은 x86 or x86-64 ISA를 이해하고 아이폰은 ARM ISA를 이해 하기 때문에 exe를 그냥 돌릴수 없다고 하셨습니다. 그런데 여기서 드는 질문은 그럼 apk를 컴퓨터(윈도우를 예시로 하면)에서 돌리면 안됩니다. 근데, 애뮬레이터를 설치하고 나면 갑자기 apk가 그 애뮬래이터에 연동됩니다. apk를 x86 or x86-64 cpu ISA용으로 바꾼것이 아닌데 어떻게 컴퓨터에서 읽히는지 알고싶습니다.(혹시 애뮬래이터의 작동 원리를 봐야 한다면 좋은 글 링크도 주시면 감사하겠습니다.)

**Comment by kangtegong** [comment]
안녕하세요!
애뮬레이터는 일종의 가상 CPU 역할을 포함하고 있기 때문에
다른 ISA의 코드를 보고 실제 실행 가능한 ISA로  변환하는 과정이 있습니다.
말하자면 애뮬레이팅할 대상을 흉내내는 프로그램인 셈이지요.

잠깐 찾아본 결과 [이 링크](https://medium.com/naver-cloud-platform/%EB%84%A4%EC%9D%B4%EB%B2%84%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-%EA%B8%B0%EC%88%A0-%EA%B2%BD%ED%97%98-%EA%B0%80%EC%83%81%ED%99%94-%EA%B0%9C%EB%85%90-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-1-qemu-vs-kvm-962113641799)의 글이 도움이 될 듯 합니다 :) 

감사합니다!
