### ISSUE TITLE
인터럽트 관련 질문입니다.

### ISSUE THREAD

**Issue by forrest1398** [kangtegong/self-learning-cs#75]
명령어 사이클 관련해서 질문이 있습니다.
- 먼저 제가 이해한 내용을 설명 드리면, 137p 그림의[ 인터럽트 사이클 -> 인출 사이클 ] 부분의 과정이 
  **1. 인터럽트 서비스 루틴 실행 및 종료
  2. 스택 영역에 백업해 두었던 데이터들을 인출**
 
라고 이해했는데 이게 맞게 이해한 것인지 확신이 들지 않아서요.. 맞게 이해한 건지 확인 부탁드립니다.
(책과 강의 정말 잘 보고 있습니다!)

**Comment by kangtegong** [comment]
넵 맞습니다,

좋게 봐주셔서 감사합니다.
새해 복 많이 받으세요!

**Comment by forrest1398** [comment]
저도 감사합니다 새해 복 많이 받으세요!!
