### ISSUE TITLE
안녕하세요 컴퓨터 공학 강의 13강 문의드립니다.

### ISSUE THREAD

**Issue by CodeNewbieee** [kangtegong/self-learning-cs#76]
댓글의 내용중 저도 비슷한 궁금증이 있어서 이슈에 적어서 문의드립닏.

책에 보면 멀티 스레드 프로세서가 슈퍼 스칼라 구조를 사용할 수 있다고 나와있는데 제가 이해한게 맞는걸까요?

1. 멀티 스레드 프로세서는 하나의 코어에서 여러 명령어를 동시에 처리할 수 있음.
2. 그게 가능한 이유는 명령어를 처리하기 위한 레지스터 세트(PC, MAR, MBR 등..)이 여러개 있기 때문
3. 명령어 파이프 라이닝은 명령어 처리 과정인 인출, 해석, 실행, 저장의 단계가 겹치지 않으면 명령어를 동시에 실행할 수 있음.
4. 명령어 파이프 라이닝이 여러개 있는 구조가 슈퍼 스칼라
5. 슈퍼 스칼라는 명령어 파이프 라이닝이 여러개 있기 때문에 3번에서 말한 인출, 해석, 실행, 저장의 단계가 겹치더라도 서로 다른 파이프 라이닝에서는 독립적으로 명령어가 실행됨.

6. 서로 다른 명령어 파이프 라이닝에서 각각 명령어1과 명령어2가 실행될 때, 명령어1은 스레드1, 명령어2는 스레드2를 통해 실행됨 (이 부분에 대한 피드백이 필요합니다.)

동시에 여러개 파이프라인(독립적인)
을 둬서 
하나의 파이프라인이 한개의 스레드로 동작하는건가요?

**Comment by kangtegong** [comment]
네 맞습니다. :)
각 명령어 파이프라인은 각기 다른 스레드로 실행될 수 있습니다(6번)
