### ISSUE TITLE
운영체제

### ISSUE THREAD

**Issue by CodeNewbieee** [kangtegong/self-learning-cs#77]
안녕하세요

다름이 아니라,
코틀린 및 안드로이드 스튜디오 공부중인데(앱개발)
비전공자로서 혼공컴운을 공부하는것이 도움이 될까요?

안드로이드 os에 대한 전체적인 설명해주는곳이 없어서
일단 기본인 컴퓨터구조및 운영체제를 알려주는 책과 강의를 보게되었는데

실례가 안된다면 여쭤보고 싶습니다. ㅠㅠ

**Comment by kangtegong** [comment]
안녕하세요,
운영체제 종류를 막론하고 알아야 할 운영체제 지식이 포함되어 있으며
개발 직군을 막론하고 (비전공자라면 더욱) 운영체제에 대한 배경지식은 중요합니다.

따라서 도움이 될 것이라 예상합니다.
