### ISSUE TITLE
오탈자 문의드립니다. (3쇄 58p)

### ISSUE THREAD

**Issue by learner-nosilv** [kangtegong/self-learning-cs#78]
안녕하세요, 혼공컴구를 들으면서 혼공학습단도 하고있는 어느 한 학생입니다.
그렇게 큰 오탈자는 아니지만, 혼공학습단 디코방에서 언급이 되어서 알려드리러 왔습니다! 

사진을 보시면 아시겠지만,
58p에 `이진수8` 표기를 0b1000 로 한다고 도식화되어있고,
61p엔 `십육진수15` 표기를 0x15 로 한다고 도식화되어있습니다.

책에 십육진수15표기 = 0x15 (십진수로 21)라고 쓰여있기도하고
또, 이진수엔 8이 없고, 십진수 8이 이진수로 1000이기 때문에
58p는 `이진수1000` 표기를 0b1000 로 한다고 하거나 `십진수8` 표기를 0b1000 로 한다고해야 더 맞는 표현인 것 같아서 이슈남겨드립니다.

![image](https://github.com/kangtegong/self-learning-cs/assets/80045214/b1b190d3-5dd8-4802-9d5f-86a9ccb75998)

**Comment by kangtegong** [comment]
안녕하세요!
꼼꼼한 독서에 진심으로 감사드립니다
이진수'로' 8표기
십육진수'로' 15 표기에서 '로'를 생략하다보니 혼동이 발생한 것 같은데요
작성해주신 소중한 피드백도 반영해보겠습니다.
감사합니다.
