### ISSUE TITLE
29강 파이썬으로 프로세스 확인하기 질문

### ISSUE THREAD

**Issue by CodeNewbieee** [kangtegong/self-learning-cs#79]
강의 잘 듣고 있습니다. 
다름이 아니라
파이선 코드로
child = Process(target=foo).start() 부분이 
fork system call에 해당하는 건가요?  (프로세스 복제?)

그리고 
foo/bar/baz 로 수행하는 작업을 다르게 할 때 
target=bar or target=baz 로 두고 실행 시키면 fork 이후에 exec system call 까지 자동적으로 처리되는 건지 궁금합니다.

**Comment by kangtegong** [comment]
엄밀히 말하자면 시스템 콜은 아닙니다. 
정확히는 C언어 예제의 fork / exec이 시스템 콜이라 볼 수 있습니다.

다만 Python 예제에서의 fork도 
실제 시스템 콜과 유사하게 동작합니다 :)
