### ISSUE TITLE
p. 175 확인 문제 2번 질문있습니다.

### ISSUE THREAD

**Issue by Youngsdog** [kangtegong/self-learning-cs#8]
2. RISC 에 대한 설명 중 올바르지 않은 것을 고르세요.
 1.  CISC보다 프로그램을 실행하는 명령어 수가 적습니다.
 2.  CISC보다 다양한 메모리 접근 방식이 있습니다.
 (이하 생략)

1번 2번 둘 다 올바르지 않다고 생각합니다.
RISC는 메모리에 접근하는 방법을 load, store 두 개로 제한할 만큼 메모리 접근을 단순화하고 최소화를 추구합니다.(p.173)에 따르면 2번도 잘못된거 아닌가요?

**Comment by kangtegong** [comment]
안녕하세요,
해당 부분은 오탈자로 
곧 진행되는 2쇄에 반영될 예정입니다.
예리하게 짚어주셔서 감사드립니다^^
