### ISSUE TITLE
40강 쓰기시 복사 질문

### ISSUE THREAD

**Issue by CodeNewbieee** [kangtegong/self-learning-cs#80]
부모프로세스로부터 나온
자식 프로세스가 처음부터 새로운 메모리에 적재되면
메모리공간을 낭비 할 수 있어서

초기 복사된 자식프로세스가 기존의 프로세스끼리 자원을 공유하지 않는다는 법칙을 넘어
부모프로세스와 동일한 프레임을 참조하는것으로 들었습니다.

그 이후에 특정 페이지번호에서 쓰기를하고 싶을 때 관련된 페이지에 대해서 프레임을 복사하여 새로운 메모리에서 관련 작업을 하는것으로 영상을 보고 받아들였는데요

그러면

쓰기시 복사의 이점은

초기에 자식 프로세스가 새로운 메모리에 적재되지 않도록하여 낭비를 줄이고
그때 그때 필요한 작업 수행할때에만 새로운 메모리에 적재(복제)되도록하는걸로 이해하면 되나요?

초기부터 자식 프로세스가 모든 페이지에 대해서 프레임을 할당받으면 컴퓨터 입장에서 생성 속도도 영향이 있으니
기존 부모 프로세스의 프레임을 가리키도록 하여 생성시간도 줄이고, 메모리 공간도 확보하는 느낌으로요

**Comment by kangtegong** [comment]
네 그렇습니다 :)
