### ISSUE TITLE
183쪽 대역폭(data rate) 용어 관련

### ISSUE THREAD

**Issue by koir1100** [kangtegong/self-learning-cs#81]
안녕하세요~ 이번에 혼공학습단 11기로 참여중인 혼공러입니다.

이번주 부분인 6장부터 공부하고 있는데,
183쪽 DDR SDRAM 부분에서 Double Data Rate 에서 사용되는
Data Rate를 대역폭으로 기술되었더라구요.

그런데 제가 알고 있는 대역폭은 bandwidth 라는 용어가 더 익숙해서요...
책에서는 설명을 위해 도로 폭이 넓으면 "전송 속도"가 빠르니 이러한 측면에서 대역폭이란 용어를 쓰신 걸로 생각합니다.

ChatGPT에 이것저것 물어봤는데 다음과 같이 알려주었습니다.

> 1. **DDR (Double Data Rate):**
>    - DDR refers to the way data is transferred in RAM.
>    - It doesn't replace the term "bandwidth."
>    - DDR means that data is transferred twice per clock cycle, which increases the effective speed without changing the actual clock speed.
> 
> 2. **Bandwidth:**
>    - Bandwidth is like the capacity of a data path.
>    - It's how much data can be transferred in a given time.
>    - DDR increases effective speed, but bandwidth is about how much can be transferred at once.
> 
> In essence, DDR improves the speed of data transfer within RAM, while bandwidth is about the overall capacity or how much data can be handled in a specific time period. They are related concepts but address different aspects of data transfer.

어찌보면 사소한 용어다보니 그냥 그렇구나 하고 넘어갈 수 있어 보입니다...
하지만 명확하게 궁금증을 해소하는 편이 좋을 듯 해서 저자님께 질문 드립니다.
관련해서 답변 부탁드리겠습니다. 감사합니다.

**Comment by kangtegong** [comment]
안녕하세요,
답이 늦어 죄송합니다.

Double Data Rate의 대중적인 한국말 번역이 대역폭이라 그렇게 작성하였습니다만,
말씀하신것처럼 유사한 용어 정도로 넘어가도 무방합니다.

![스크린샷 2024-01-21 오후 10 16 40](https://github.com/kangtegong/self-learning-cs/assets/47781146/bf630eca-eab9-43ba-8dda-da35b0a68138)

사실 대역폭이라는 용어는 
아래와 같이 신호 처리에서의 용어와 컴퓨팅에서의 용어가 나뉘어지기도 하고, 
이에 대한 설명을 하지 않은 것 뿐이라서요.

![스크린샷 2024-01-21 오후 10 18 48](https://github.com/kangtegong/self-learning-cs/assets/47781146/15375177-e67f-49d6-bbfd-52ea55ea73a1)

감사합니다.
