### ISSUE TITLE
414 쪽 "참조 비트", "접근 비트" 용어 통일이 필요할까요?

### ISSUE THREAD

**Issue by hyoseok0** [kangtegong/self-learning-cs#82]
안녕하세요?
공부하면서 많은 도움을 받고 있습니다!

중요하진 않지만ㅎ Chapter 14 가상 메모리의 414 쪽에 "참조 비트"와 "접근 비트" 용어가 같이 쓰이는데요~ 
하나로 통일되면 어떨까 합니다ㅎ
아래와 같이 사용되는 거 같네요.

- "참조 비트는 CPU 가 이 페이지에 접근한 적이 있는지 여부를 나타냅니다."
- "접근 비트는 페이지에 접근한 적이 있는지를 나타냅니다."

**Comment by kangtegong** [comment]
안녕하세요 :)
도움을 받고 계시다니 다행이고, 또 감사드립니다.

두 용어 모두 같은 의미를 지닙니다.
말씀하신대로 일관성을 위해 통일되면 더욱 좋을 것 같습니다.
다음 쇄에 반영토록 하겠습니다. 짚어주셔서 감사드릡니다.

**Comment by koir1100** [comment]
안녕하세요~ 출판사 오탈자 페이지에서 말씀하신 부분이 반영된 걸로 보입니다.
[출판사 페이지](https://www.hanbit.co.kr/media/books/book_view.html?p_code=B9177037040)

확인하시면 좋을 듯 합니다! 감사합니다!

![IMG_0521](https://github.com/kangtegong/self-learning-cs/assets/4710834/d560400f-0573-4b69-9597-4766fb525e9d)

**Comment by koir1100** [comment]
> 안녕하세요~ 출판사 오탈자 페이지에서 말씀하신 부분이 반영된 걸로 보입니다. [출판사 페이지](https://www.hanbit.co.kr/media/books/book_view.html?p_code=B9177037040)
> 
> 확인해 보시면 좋을 듯 합니다! 감사합니다!
> 
> ![IMG_0521](https://private-user-images.githubusercontent.com/4710834/302181254-d560400f-0573-4b69-9597-4766fb525e9d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjg4MDcsIm5iZiI6MTcwNzEyODUwNywicGF0aCI6Ii80NzEwODM0LzMwMjE4MTI1NC1kNTYwNDAwZi0wNTczLTRiNjktOTU5Ny00NzY2ZmI1MjVlOWQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEwMjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNzU1MmM3MzIyY2YxODk5ZTcwYzQ2Y2ExMzg2YWI4OGVhNTFhNDc1ZWIwMTI1NGQ0YWQxMzIxZWVkODMyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xyGKS_QVOrN5HRFwRUGLQF-gPoG9wPK--IGoRO5_dmg)

저자님! 422쪽 마무리 핵심 포인트 "페이지 테이블"에서 접근 비트 용어가 사용되었네요!
이 부분 추가로 반영해주시면 좋을 듯 합니다.
감사합니다!!
