### ISSUE TITLE
모니터 자바 예제 코드 syncronization 오탈자 문의

### ISSUE THREAD

**Issue by yoon6763** [kangtegong/self-learning-cs#83]
안녕하세요.

동기화 기법 - 모니터 부분의 자바 예제 코드를 복붙해봤는데,
syncronized 키워드에 컴파일 에러가 발생하더라고요.
혹시 synchronized를 오타내신건가 싶어 문의드립니다.

https://github.com/kangtegong/self-learning-cs/blob/main/synchronization/syncronization.md

![image](https://github.com/kangtegong/self-learning-cs/assets/74063259/8a0bbcea-9a2f-435a-99bc-f154fdd7ad20)

**Comment by kangtegong** [comment]
헉 맞습니다.. 오타입니다.  바꾸어두었습니다. 짚어주셔서 감사드립니다.
