### ISSUE TITLE
243p 메모리맵 입출력 및 고립형 입출력 질문

### ISSUE THREAD

**Issue by brightree** [kangtegong/self-learning-cs#84]
안녕하세요?
1. 메모리 맵 입출력은 메모리에 접근하기 위한 주소 공간과 입출력장치에 접근하기 위한 주소공간을 하나의 주소 공간으로 간주하는 방식이라고 설명해주셨습니다. 여기서 말하는 컴퓨터의 '주소 공간'은 컴퓨터의 메모리에 할당되어 있는 것일까요?

2. 고립형 입출력 예시에서, 1024개의 주소 공간을 가진 컴퓨터가 있을 때 메모리도 1024개의 주소 공간을 활용할 수 있고 입출력장치도 1024개의 주소 공간을 활용할 수 있다고 설명해주셨습니다.
다만 헷갈리는 부분이, 메모리와 입출력장치 각각 1024개의 주소공간을 활용할 수 있다는 것은 (1024개의 주소공간을 가진 컴퓨터에서) 총 2048개의 주소공간을 활용한다는 것이 아닌가요?
만약 메모리와 입출력장치가 1024개의 주소공간을 겹치지 않게 활용할 수 있다는 의미라면, 두 장치가 같은 주소공간을 활용하려고 하는 시도를 방지하는 절차가 존재하는지 궁금합니다.

감사합니다!!!

**Comment by kangtegong** [comment]
안녕하세요, 하나씩 답변드리겠습니다.

1. 주소 공간이란 실제 물리적으로 접근 가능한 공간이라기보다는 CPU가 인식할 수 있는 주소의 범위라고 이해해주시는 것이 좋습니다 :)
2. p243에 명시된 입출력장치 읽기/쓰기 버스가 그 방법입니다. 버스에 ‘메모리 읽기/쓰기’ 선 이외에 ‘입출력장치 읽기/쓰기’ 선이 따로 있다면, 같은 100번지에 접근하더라도 입출력장치 읽기/쓰기 버스가 활성화되어 있을 경우 입출력장치 100번지에 접근하고, 메모리 읽기/쓰기 버스가 활성화될 경우 메모리에 접근하게됩니다. 이렇게 같은 주소에 접근하더라도 다른 메모리/입출력장치에 달리 접근할 수 있습니다.
