### ISSUE TITLE
379쪽 식사하는 철학자 그림 관련

### ISSUE THREAD

**Issue by koir1100** [kangtegong/self-learning-cs#85]
안녕하세요~~ 혼공학습단 11기 혼공러입니다.
5주차 진도를 마쳤습니다.
남아 있는 부분까지 잘 주파하여 마무리할 수 있도록 하겠습니다.

이번에 말씀드릴 내용은
379쪽의 자원 할당 그래프와 연계하여
(사각형 식탁에 앉아있는)
식사하는 철학자 그림에 관한 부분입니다.

367쪽의 그림 기준으로 10시 방향에 있는 철학자부터
반시계 방향으로 해서 (우리가 보기에) 오른쪽에서 왼쪽 순으로 앉아 있는 그림이라 생각됩니다.

규칙 상 왼손으로 먼저 포크를 들 수 있도록 포크가 놓여야 합니다.
하지만 철학자 기준으로 봤을 때는 오른손으로 포크를 들 수 있도록
포크 위치가 잘못 놓여진 걸로 생각됩니다.

그래서 다음과 같이 그림을 수정하면 좋을 거 같아 건의드립니다.

![식사하는 철학자 수정 건의 이미지](https://github.com/kangtegong/self-learning-cs/assets/4710834/8977d6c2-8b4e-415f-b4ad-881455cbe1a1)

아무쪼록 "혼자 공부하는 컴퓨터 구조+운영체제" 를 통해
더욱 발돋움하는 개발자가 되겠습니다.

내용 확인하시고 답변 부탁드리겠습니다.

감사합니다.

**Comment by kangtegong** [comment]
안녕하세요,
좋은 의견 참고하겠습니다.
꼼꼼히 읽어주셔서 감사드립니다 :)
