### ISSUE TITLE
292쪽  프로세스 메모리영역에 대해 질문드립니다.

### ISSUE THREAD

**Issue by hyewoon** [kangtegong/self-learning-cs#87]
안녕하세요 저자님! 책과 강의 제공해 주셔서 감사합니다.

10장 프로세스와 스레드를 공부하는 중에 궁금한 점이 생겨 두 가지 질문드립니다. 

질문1 :  292쪽 프로세스 메모리 영역  '하나의 프로세스는 코드, 데이터, 힙, 스택 영역으로 나눠 저장된다.' 라는 부분에서 첨부한 사진처럼 프로세스별로 개별적인 스택, 힙, 데이터, 코드 영역을 갖는다고 이해하는 게 맞을까요? 
<img width="325" alt="image" src="https://github.com/kangtegong/self-learning-cs/assets/113662682/983d02c6-b67e-4dac-b391-f22d26d89c67">

질문 2 : 추가적으로, 100쪽에서 '스택과 큐' 저장공간에 대해 설명해 주셨는데, 그렇다면  큐는 메모리 어디에 위치하는지가 궁금해졌습니다. 첨부한 사진처럼 따로 큐 영역이 존재한다고 이해하는 것이 맞을까요? 
<img width="363" alt="image" src="https://github.com/kangtegong/self-learning-cs/assets/113662682/e5188e52-5573-40e4-bc4b-0dd8ad7f29db">

답변 부탁드리겠습니다. 
 날씨가 추운데 건강 잘 챙기시기 바랍니다. 감사합니다.

**Comment by kangtegong** [comment]
안녕하세요, 좋게 읽어주셔서 감사드립니다.

**질문1**

네 맞습니다. 프로세스마다 개별적인 스택, 힙, 데이터, 코드 영역을 갖습니다.

**질문2**

스택과 달리 큐는 명시적으로 지정된 영역이 없습니다.
(단순히 저장된 순서대로 추출하면 되므로, 큐는 일반적인 저장공간으로도 간단히 구현할 수 있습니다. )

건강하시기 바랍니다.
감사합니다.

**Comment by hyewoon** [comment]
답변 감사합니다!!
