### ISSUE TITLE
8장 입출력 장치 내용 중 "주소 공간"

### ISSUE THREAD

**Issue by seona-jung** [kangtegong/self-learning-cs#9]
안녕하세요 저자님,
집필해주신 책으로 동기들과 함께 스터디를 진행하고 있습니다.
감사합니다.

8장을 읽다가 "주소 공간"이라는 단어를 봤는데 이게 무얼 뜻하는지 잘 모르겠어서 질문드립니다.

08-2 다양한 입출력 > 프로그램 입출력 > 메모리 맵 입출력 & 고립형 입출력 모두에서 "주소 공간"이 등장하는데
스터디원들과 상의를 해봤는데도 그 의미를 잘 모르겠어서 질문드립니다.

"주소 공간"이 어떤 걸 의미하는 것인가요?

감사합니다.

**Comment by kangtegong** [comment]
안녕하세요, 좋게 읽어주셔서 감사합니다.
입출력장치 장을 읽어보면 장치 컨트롤러라는 이야기가 나옵니다.
그 장치 컨트롤러에 레지스터가 있다고도 언급했었지요.
(추가로 해당 장의 막바지에는 입출력 장치 중 메모리를 내장하고 있는 입출력장치도 많다고 언급했었습니다)

주소 공간은 입출력장치의 컨트롤러 속 레지스터 (혹은 메모리)를 의미합니다.
가령 입출력장치마다 레지스터가 10개 있다고 단순 가정했을 때,
10개의 입출력 장치가 있다면 레지스터는 100개
100개의 입출력장치가 있다면 레지스터는 1000개가 되겠지요.

CPU 입장에서는 입출력장치 속 각각의 레지스터(혹은 메모리)와 정보를 주고받으려면 
각각의 레지스터(메모리 주소)를 특정지을 수 있어야겠죠?
이렇게 입출력장치 내의 특정 저장 공간을 특정지을 수 있는 정보를 주소공간이라고 합니다.
