### ISSUE TITLE
C/C++로 프로세스 다루기 소스 코드 관련

### ISSUE THREAD

**Issue by JangIn-40** [kangtegong/self-learning-cs#90]
안녕하세요 저자님  우선 책 잘읽고있습니다!
다름이 아니라 C/C++로 프로세스 다루기 첫번째 소스코드에서 include에 #이 안붙어있습니다. 엄청 사소한건데 혹시나 싶어 질문남깁니다. ㅎㅎ; 그리고 유투브도 잘 봤습니다! 나중에 시간이 남으신다면 새로운 영상 부탁드립니다..
감사합니다!

**Comment by kangtegong** [comment]
감사합니다^^ 덕분에 수정할 수 있었습니다.
바쁜 출간 시기가 지나 이제 곧 새 영상을 올릴 예정입니다.
기다려주셔서 감사합니다.
즐거운 주말 되시기 바랍니다^^
