### ISSUE TITLE
48페이지 시스템 버스에 대해서 질문합니다.

### ISSUE THREAD

**Issue by kwan102608** [kangtegong/self-learning-cs#94]
시스템 버스의 주소버스, 데이터버스, 제어버스 이렇게 3가지가 있다고 했는데, 궁금한점은 데이터버스와 제어버스가 이미 올바른 주소로 전송될텐데 주소버스가 따로 존재하는 이유를 잘 모르겠습니다. 버스끼리는 그림상 모두 단절되있어서 도중에 주소나 데이터를 서로 합치거나 변형할수도 없을꺼고, 메모리등 장치에서 각 3개의 버스로 온 정보를 다시 합칠꺼면 굳이 버스라인을 나누는 것보다 첨부터 정보를 합쳐서 보내는게 더 효율적일테고, 왜 굳이 주소버스, 데이터버스, 제어버스를 각기 다른 길로 만들어서 전송하는지 그 효용과 효율을 잘 모르겠습니다. 

답변부탁합니다. 그리고 책이 재밌습니다. 감사합니다.

**Comment by kangtegong** [comment]
안녕하세요!
(알림을 늦게 확인하여 답변이 늦었습니다, 죄송합니다..)

데이터버스와 제어버스가 이미 올바른 주소로 전송될텐데 주소버스가 따로 존재하는 이유를 잘 모르겠습니다. 

데이터 버스와 제어 버스에는 주소에 대한 정보가 없습니다. 
주소 버스를 통해 주고받는 위치 정보가 있어야 합니다.

추가로 주소를 주고받는 빈도는 데이터, 제어신호만큼 잦아
별도의 버스로 만드는 것이 좋습니다.
