### ISSUE TITLE
422 page 확인 문제 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by seungkoo-jeong** [kangtegong/self-learning-cs#95]
책 내용 중 적재 이후 CPU가 읽거나 쓴 페이지는 참조 비트가 1로 세팅된다고 되어 있는데요.
422 page 확인 문제 2번 그림을 보면, 참조비트가 0이고, 수정비트가 1인데,
수정 비트가 1이라는 건 참조가 되었다는 거 아닌가요?
참조비트가 0인데, 수정비트가 1인 경우가 있을 수 있는지 궁금합니다.

**Comment by kangtegong** [comment]
안녕하세요!

그러한 경우도 있습니다.
페이지 교체 알고리즘 중 참조 비트를 바꿀 수 있는 것도 있기 때문입니다.
p428의 2차 기회 페이지 교체 알고리즘을 보신다면,
참조 비트를 0으로 바꾼뒤 다시 기회를 준다는 것을 알 수 있을 것입니다 :)

수정비트는 보조기억장치에 추가적인 쓰기를 해야하는지 여부를 나타내는 비트이기 때문에
이 경우 참조 비트가 0 수정비트가 1이 됩니다.
