### ISSUE TITLE
register 크기 관련 질문

### ISSUE THREAD

**Issue by LeEHaNa1** [kangtegong/self-learning-cs#96]
register의 크기가 32bit도 있고 64bit도 있다고 하는데, 크기라는 것이 정확히 어떤 의미인지 잘 모르겠어요. 물리적인 register의 크기는 차이가 없고 저장할 수 있는 크기가 32bit, 64bit로 차이가 나는 건가요?

**Comment by LeEHaNa1** [comment]
추가로 질문이 생겨, 질문 남깁니다. ISA마다 정의하는 register의 개수와 종류가 다르다고 알고 있습니다. 그럼 MAR, MBR, IR 같은 register들은 ISA의 영향을 받지 않고 별개로 CPU에 존재한다고 이해하는 게 맞을까요?

**Comment by kangtegong** [comment]
안녕하세요, 하나씩 답변 드리겠습니다.

> register의 크기가 32bit도 있고 64bit도 있다고 하는데, 크기라는 것이 정확히 어떤 의미인지 잘 모르겠어요. 물리적인 register의 크기는 차이가 없고 저장할 수 있는 크기가 32bit, 64bit로 차이가 나는 건가요?


물리적인 레지스터 크기가 다를 수도 있고 저장 공간이 다를 수도 있습니다. 이건 CPU마다 차이가 있을 듯 해요.
"저장할 수 있는 크기가 32bit, 64bit로 차이가 있음" 정도로 기억하시는 것이 좋을 것 같습니다.

> ISA마다 정의하는 register의 개수와 종류가 다르다고 알고 있습니다. 그럼 MAR, MBR, IR 같은 register들은 ISA의 영향을 받지 않고 별개로 CPU에 존재한다고 이해하는 게 맞을까요?

CPU  종류(ISA)를 막론하고 거의 대부분 존재하기는 합니다. 다만 ISA마다 IR의 값을 디코딩하는 방식, 주소를 해석하는 방식 등은 조금씩 차이가 있을수 있습니다.
