### ISSUE TITLE
직접 주소 지정 방식 vs 간접 주소 지정 방식

### ISSUE THREAD

**Issue by keizikang** [kangtegong/self-learning-cs#97]
간접 주소 지정 방식에 대해, 책에 이렇게 설명이 되어 있는데요.

"직접 주소 방식보다 표현할 수 있는 유효 주소의 범위가 더 넓어졌다."

여기서 말하는 '주소의 범위가 더 넓다'는 것이 정확히 무엇인지 모르겠습니다.

1. 오퍼랜드가 더 짧다?
  * 이건 아닐 것 같은게.. 주소는 모두 같은 길이가 아닐까 합니다.
  * 예를 들면 0x0000부터 0xFFFF까지... 이런 식으로요.
2. 주소의 범위가 더 넓다?
  * 예를 들어 메모리가 총 128칸(?)이라면,
  * 데이터는 이 중 32칸에만 담을 수 있지만,
  * 주소는 모든 칸에 넣을 수 있다.
  * 이게 맞다면, 왜 그렇게 설계(?)되어 있는지도 궁금합니다.

아니면 둘 다 아닐까요?

고맙습니다.

**Comment by kangtegong** [comment]
안녕하세요,
비슷한 질문이 과거에 다음과 같이 있었는데, 참고하시면 이해하실 수 있을 듯 합니다.
요지는 '한 메모리 주소를 통째로 데이터 저장에 활용할 수 있다는 것'입니다.

https://github.com/kangtegong/self-learning-cs/issues/26

https://github.com/kangtegong/self-learning-cs/issues/10
