### ISSUE TITLE
godbolt.org 사이트에서 linux, ubuntu의 어셈블리어

### ISSUE THREAD

**Issue by otation** [kangtegong/self-learning-cs#98]
안녕하세요.

교재 구매 및 유튜브통해서 학습중입니다.

유튜브내용 중 godbolt.org에서 어셈블리어로 변경되는것을 해보고있는데, 언어선택창에 linux코드는 따로 없는 것 같습니다.
단순하게 사이트에서 제공을 안하는 것인지, linux는 방식이 다른것인지 문의드립니다.
가능하다면 linux도 어셈블리어로 볼수있는 사이트가 있는지요

감사합니다.

**Comment by kangtegong** [comment]
안녕하세요!
나와 있는 내용은 언어 선택 창과는 무관한 내용인 듯 합니다 :)
리눅스에서 작성한 내용이 어셈블리어로 변환되어도 동일하게 때문에
(CPU 종류와 컴파일러 종류 등이 중요하고, 작성한 C 코드는 운영체제와 무관한 내용이기 때문에)
운영체제의 종류는 명시되지 않은 것으로 보입니다 :)
