### ISSUE TITLE
TCB에 대해서 소개하실 생각이 있으실까요?

### ISSUE THREAD

**Issue by ChoiSeonMun** [kangtegong/self-learning-cs#99]
안녕하세요, 저자님. 먼저, 훌륭한 책을 써주신 것에 감사드립니다.
10장 프로세스와 스레드 쪽을 쭉 보면서 TCB(Thread Control Block)에 대한 내용이 들어간다면
독자의 이해가 좀 더 풍성해지지 않을까 하는 생각이 들었습니다. 
이에 대해 저자님의 의견이 궁금합니다.

**Comment by kangtegong** [comment]
안녕하세요~
좋은 의견 감사드립니다^^
개정 출판이 된다면 추가 고려해 보겠습니다

감사합니다
